package com.github.tartaricacid.touhoulittlemaid.sim.debug;
import com.google.gson.*;
import java.io.IOException;
final class KneekuraDebugOwnerDispatch {
 private KneekuraDebugOwnerDispatch(){}
 static String actionKey(KneekuraDebugOwnerInputs input,String actionId){var id=input.grant().identity();JsonObject body=new JsonObject();body.addProperty("actionId",actionId);body.addProperty("processEpoch",id.processEpoch());body.addProperty("requestHash",input.grant().requestHash());body.addProperty("runId",id.runId());body.addProperty("runSnapshotId",id.runSnapshotId());return KneekuraDebugActionJournal.sha256(KneekuraDebugActionJournal.canonical(body));}
 static String cleanupKey(KneekuraDebugOwnerInputs input){var id=input.grant().identity();JsonObject b=new JsonObject();b.addProperty("operation","owner_cleanup_reset");b.addProperty("processEpoch",id.processEpoch());b.addProperty("requestHash",input.grant().requestHash());b.addProperty("runId",id.runId());b.addProperty("runSnapshotId",id.runSnapshotId());return KneekuraDebugActionJournal.sha256(KneekuraDebugActionJournal.canonical(b));}
 static String captureKey(KneekuraDebugOwnerInputs input,int index){var id=input.grant().identity();JsonObject body=new JsonObject();body.addProperty("captureIndex",index);body.addProperty("processEpoch",id.processEpoch());body.addProperty("requestHash",input.grant().requestHash());body.addProperty("runId",id.runId());body.addProperty("runSnapshotId",id.runSnapshotId());return KneekuraDebugActionJournal.sha256(KneekuraDebugActionJournal.canonical(body));}
 static JsonObject action(KneekuraDebugOwnerInputs input,String selected,long epoch,long revision)throws IOException{
  JsonObject original=null;for(JsonElement e:input.actions())if(KneekuraDebugOwnerInputs.t(e.getAsJsonObject(),"action_id").equals(selected)){original=e.getAsJsonObject();break;}if(original==null)throw new IOException("SELECTED_ACTION_NOT_RETAINED");var id=input.grant().identity();JsonObject result=new JsonObject();result.addProperty("schemaVersion",1);result.addProperty("debugSessionId",id.debugSessionId());result.addProperty("runId",id.runId());result.addProperty("runSnapshotId",id.runSnapshotId());result.addProperty("processEpoch",id.processEpoch());result.addProperty("experimentId",id.experimentId());result.addProperty("arenaId",input.grant().arena().arenaId());result.addProperty("arenaEpoch",epoch);result.addProperty("expectedArenaRevision",revision);result.addProperty("actionId",selected);result.addProperty("idempotencyKey",actionKey(input,selected));result.addProperty("type",KneekuraDebugOwnerInputs.t(original,"operation"));JsonObject args=original.deepCopy();args.remove("operation");args.remove("action_id");result.add("args",args);return result;
 }
 static void validate(KneekuraDebugOwnerInputs input,JsonObject dispatch,JsonObject payload,byte[] canonical,int nextIndex)throws IOException{
  KneekuraDebugActionJournal.keys(dispatch,"schemaVersion","ownerEnvelopeHash","runSnapshotId","runSnapshotHash","requestHash","handshakeNonce","leaseId","selectedActionId","idempotencyKey","payloadHash");base(input,dispatch);String selected=KneekuraDebugOwnerInputs.t(dispatch,"selectedActionId");JsonArray actions=input.actions();if(nextIndex<0||nextIndex>=actions.size()||!selected.equals(KneekuraDebugOwnerInputs.t(actions.get(nextIndex).getAsJsonObject(),"action_id")))throw new IOException("ACTION_ORDER_CONFLICT");
  if(!KneekuraDebugOwnerInputs.t(dispatch,"idempotencyKey").equals(actionKey(input,selected))||!KneekuraDebugOwnerFiles.sha256(canonical).equals(KneekuraDebugOwnerInputs.t(dispatch,"payloadHash")))throw new IOException("ACTION_KEY_OR_PAYLOAD_CONFLICT");JsonObject expected=action(input,selected,KneekuraDebugOwnerInputs.n(payload,"arenaEpoch"),KneekuraDebugOwnerInputs.n(payload,"expectedArenaRevision"));if(!payload.equals(expected))throw new IOException("ACTION_DIFFERS_FROM_RETAINED_REQUEST");
 }
 static void validateCapture(KneekuraDebugOwnerInputs input,JsonObject marker,java.util.Set<Integer> usedSlots)throws IOException{
  JsonObject shape=marker.deepCopy();shape.remove("trigger");
  KneekuraDebugActionJournal.keys(shape,"schemaVersion","ownerEnvelopeHash","runSnapshotId","runSnapshotHash","requestHash","handshakeNonce","leaseId","captureIndex","captureKey","captureId","expectedArenaEpoch","expectedArenaRevision");base(input,marker);long index=KneekuraDebugOwnerInputs.n(marker,"captureIndex");if(usedSlots.contains((int)index)||index<0||index>=input.grant().maxCaptures()/4||!KneekuraDebugOwnerInputs.t(marker,"captureKey").equals(captureKey(input,(int)index))||!KneekuraDebugOwnerInputs.t(marker,"captureId").equals("capture-"+captureKey(input,(int)index)))throw new IOException("CAPTURE_SLOT_OR_REPLAY_CONFLICT");
  KneekuraDebugOwnerTriggers.validateIntent(input,marker,System.currentTimeMillis());
 }
 static void validateCleanup(KneekuraDebugOwnerInputs input,JsonObject marker)throws IOException{KneekuraDebugActionJournal.keys(marker,"schemaVersion","ownerEnvelopeHash","runSnapshotId","runSnapshotHash","requestHash","handshakeNonce","leaseId","expectedArenaEpoch","expectedArenaRevision","cleanupKey");base(input,marker);if(!KneekuraDebugOwnerInputs.t(marker,"cleanupKey").equals(cleanupKey(input)))throw new IOException("CLEANUP_KEY_MISMATCH");}
 private static void base(KneekuraDebugOwnerInputs input,JsonObject marker)throws IOException{if(KneekuraDebugOwnerInputs.n(marker,"schemaVersion")!=1||!KneekuraDebugOwnerInputs.t(marker,"ownerEnvelopeHash").equals(input.envelopeHash())||!KneekuraDebugOwnerInputs.t(marker,"runSnapshotId").equals(input.grant().identity().runSnapshotId())||!KneekuraDebugOwnerInputs.t(marker,"runSnapshotHash").equals(input.snapshotHash())||!KneekuraDebugOwnerInputs.t(marker,"requestHash").equals(input.grant().requestHash())||!KneekuraDebugOwnerInputs.t(marker,"handshakeNonce").equals(input.grant().identity().handshakeNonce())||!KneekuraDebugOwnerInputs.t(marker,"leaseId").equals(input.grant().leaseId()))throw new IOException("OWNER_COMMAND_IDENTITY_MISMATCH");}
}
