import test from 'node:test';import assert from 'node:assert/strict';
import {validOriginalDecisionEvent,appendOriginalDecisionEvents} from '../original-decision-events.mjs';
const check=(checkIndex=1,result=false)=>({checkIndex,memoryModuleStatus:'AVAILABLE',memoryModule:'WALK_TARGET',requestedMemoryStatus:'VALUE_PRESENT',result});
const record=()=>({source:{side:'SERVER'},gameTime:100,observationId:'obs:req:1',payload:{schema:'kneekura.original-decision-event/v1',semantics:'ORIGINAL_INVOCATION_RETURN_ONLY',targetRevision:7,burstId:'burst:7:100',eventIndex:1,kind:'BRAIN_ACTIVITY_REQUIREMENT_CHECKS_RETURN',data:{brainClass:'net.minecraft.world.entity.ai.Brain',instanceIdentityStatus:'AVAILABLE',instanceIdentity:'component:7:1',activityInvocationId:'activity:7:1',dispatchScope:'UPDATE_ACTIVITY_FROM_SCHEDULE_ORIGINAL_VIRTUAL_CALL',fieldScope:'BASE_BRAIN_CACHED_FIELDS_ONLY',behaviorStopStatus:'NOT_EXPOSED',movementOutcomeStatus:'NOT_EXPOSED',requirementInvocationId:'activity-requirement:7:1',callerSite:'IF_POSSIBLE',requestedActivityStatus:'AVAILABLE',requestedActivity:'REST',mapContains:true,result:false,checks:[check()],checksTruncated:false,checkScope:'ORIGINAL_ACTIVITY_REQUIREMENT_MAP_AND_VIRTUAL_CHECK_RETURNS_PREFIX_NOT_ALL_ELIGIBILITY_REASONS'},observerCostNanos:1,observerCostScope:'BUILD_AND_FIRST_BYTE_CHECK_EXCLUDES_FINAL_ENCODING_WRITER'}});
test('actual Activity requirement returns are partial evaluation tied to direct original parent',()=>{const r=record();assert.equal(validOriginalDecisionEvent(r),true);const stages={},caps={};appendOriginalDecisionEvents([r],stages,caps,[]);assert.equal(stages.EVALUATION.facts.length,1);assert.equal(caps.brain_activity.status,'PARTIAL');for(const s of ['CANDIDATE','SELECTION','EXECUTION','RESULT'])assert.equal(stages[s],undefined);});
test('missing map entry and registered empty set preserve distinct original predicate results',()=>{const r=record(),d=r.payload.data;d.mapContains=false;d.checks=[];assert.equal(validOriginalDecisionEvent(r),true);d.mapContains=true;d.result=true;assert.equal(validOriginalDecisionEvent(r),true);d.callerSite='FIRST_VALID';assert.equal(validOriginalDecisionEvent(r),true);});
test('finite actual prefix retains original virtual boolean without slot reconstruction',()=>{const r=record(),d=r.payload.data;d.checks=Array.from({length:8},(_,i)=>check(i+1));d.checksTruncated=true;d.result=true;assert.equal(validOriginalDecisionEvent(r),true);d.checks.pop();assert.equal(validOriginalDecisionEvent(r),false);});
test('unknown operands/component/Activity stay unknown and normal booleans independent',()=>{const r=record(),d=r.payload.data;delete d.instanceIdentity;d.instanceIdentityStatus='NOT_EXPOSED';delete d.requestedActivity;d.requestedActivityStatus='NOT_EXPOSED';delete d.checks[0].memoryModule;d.checks[0].memoryModuleStatus='NOT_EXPOSED';d.checks[0].requestedMemoryStatus='NOT_EXPOSED';assert.equal(validOriginalDecisionEvent(r),true);});
test('reject forged scopes, causal reasons, wrong parent IDs, caps and malformed entries safely',()=>{for(const mutate of [d=>d.requirementInvocationId='activity-requirement:7:257',d=>d.activityInvocationId='activity:8:1',d=>d.reason='MISSING',d=>d.callerSite='ALL_CANDIDATES',d=>d.checkScope='ALL_REASONS',d=>d.mapContains=false,d=>d.checksTruncated=true,d=>d.checks[0].checkIndex=2,d=>d.checks[0].slotPresent=true,...[null,1,false,[], 'bad'].map(v=>d=>d.checks=[v])]){const r=record();mutate(r.payload.data);assert.equal(validOriginalDecisionEvent(r),false);assert.doesNotThrow(()=>appendOriginalDecisionEvents([r],{}, {}, []));}});
