import test from 'node:test';import assert from 'node:assert/strict';
import {validOriginalDecisionEvent,appendOriginalDecisionEvents} from '../original-decision-events.mjs';
const record=()=>({source:{side:'SERVER'},gameTime:100,observationId:'obs:memory-source:1',payload:{schema:'kneekura.original-decision-event/v1',semantics:'ORIGINAL_INVOCATION_RETURN_ONLY',targetRevision:7,burstId:'burst:7:100',eventIndex:1,kind:'BRAIN_PATH_MEMORY_SOURCE_RETURN',data:{brainClass:'net.minecraft.world.entity.ai.Brain',instanceIdentityStatus:'AVAILABLE',instanceIdentity:'component:7:1',memorySourceInvocationId:'memory-source:7:1',requirementInvocationId:'memory-requirement:7:1',tryStartInvocationId:'try-start:7:1',checkIndex:1,memoryModuleStatus:'AVAILABLE',memoryModule:'WALK_TARGET',requestedMemoryStatus:'VALUE_PRESENT',slotStatus:'NON_NULL',presenceStatus:'NORMAL_RETURN',presenceSite:'VALUE_PRESENT',presenceResult:false,baseResult:false,result:false,sourceScope:'ORIGINAL_BASE_MAP_PRESENCE_AND_RETURN_WITH_VIRTUAL_RESULT_NOT_ALL_ELIGIBILITY_REASONS'},observerCostNanos:1,observerCostScope:'BUILD_AND_FIRST_BYTE_CHECK_EXCLUDES_FINAL_ENCODING_WRITER'}});
test('original memory source links are partial evaluation under exact behavior parent',()=>{const r=record();assert.equal(validOriginalDecisionEvent(r),true);const s={},c={};appendOriginalDecisionEvents([r],s,c,[]);assert.equal(s.EVALUATION.facts.length,1);assert.equal(c.brain_navigation.status,'PARTIAL');for(const k of ['CANDIDATE','SELECTION','EXECUTION','RESULT'])assert.equal(s[k],undefined);});
test('Activity source uses its own direct parent without requiring Navigation metadata',()=>{const r=record(),d=r.payload.data;r.payload.kind='BRAIN_ACTIVITY_MEMORY_SOURCE_RETURN';delete d.tryStartInvocationId;d.activityInvocationId='activity:7:1';d.requirementInvocationId='activity-requirement:7:1';assert.equal(validOriginalDecisionEvent(r),true);const c={};appendOriginalDecisionEvents([r],{},c,[]);assert.equal(c.brain_activity.status,'PARTIAL');});
test('null slot and REGISTERED preserve no original presence call without invented value',()=>{const r=record(),d=r.payload.data;delete d.presenceSite;delete d.presenceResult;d.presenceStatus='NOT_CALLED';d.slotStatus='NULL';assert.equal(validOriginalDecisionEvent(r),true);d.slotStatus='NON_NULL';d.requestedMemoryStatus='REGISTERED';d.baseResult=d.result=true;assert.equal(validOriginalDecisionEvent(r),true);});
test('base and virtual normal booleans remain independent and unknown operands explicit',()=>{const r=record(),d=r.payload.data;d.result=true;assert.equal(validOriginalDecisionEvent(r),true);delete d.memoryModule;d.memoryModuleStatus='NOT_EXPOSED';delete d.instanceIdentity;d.instanceIdentityStatus='NOT_EXPOSED';d.requestedMemoryStatus='NOT_EXPOSED';delete d.presenceSite;delete d.presenceResult;d.presenceStatus='NOT_CALLED';assert.equal(validOriginalDecisionEvent(r),true);});
test('two actual presence sites retain true/false returns without inferring arrival',()=>{const r=record(),d=r.payload.data;for(const k of ['VALUE_PRESENT','VALUE_ABSENT'])for(const b of [false,true]){d.requestedMemoryStatus=d.presenceSite=k;d.presenceResult=b;assert.equal(validOriginalDecisionEvent(r),true);}});
test('reject mismatched IDs, forged parent/source, extra value data and malformed facts safely',()=>{for(const mutate of [d=>d.memorySourceInvocationId='memory-source:7:257',d=>d.requirementInvocationId='activity-requirement:7:1',d=>d.tryStartInvocationId='try-start:8:1',d=>d.checkIndex=9,d=>d.slotStatus='MISSING_MEMORY',d=>d.presenceSite='VALUE_ABSENT',d=>d.presenceStatus='NOT_CALLED',d=>d.requestedMemoryStatus='REGISTERED',d=>d.slotStatus='NULL',d=>d.value='REPLAYED',d=>d.sourceScope='FULL_CAUSE',d=>d.presenceResult=null,d=>d.result='true']){const r=record();mutate(r.payload.data);assert.equal(validOriginalDecisionEvent(r),false);assert.doesNotThrow(()=>appendOriginalDecisionEvents([r],{}, {}, []));}for(const v of [null,[],1,false]){const r=record();r.payload.data=v;assert.equal(validOriginalDecisionEvent(r),false);}});
