import test from 'node:test';
import assert from 'node:assert/strict';
import {validOriginalDecisionEvent,appendOriginalDecisionEvents} from '../original-decision-events.mjs';
const common=()=>({sinkClass:'net.minecraft.world.entity.ai.behavior.MoveToTargetSink',instanceIdentity:'component:7:1',instanceIdentityStatus:'AVAILABLE',computeInvocationId:'compute:7:1',callSite:'CHECK_EXTRA_START',gameTimeArgument:'100',walkTargetClass:'net.minecraft.world.entity.ai.memory.WalkTarget',enclosingSinkInvocationStatus:'NOT_CAPTURED',enclosingTickStopInvocationStatus:'NOT_CAPTURED',parentScope:'CAPTURED_ENCLOSING_SOURCE_SCOPES_NOT_IMMEDIATE_CAUSE_OR_ADOPTION',fieldScope:'BASE_CACHED_FIELDS_AT_DECLARED_CAPTURE_BOUNDARY',arrivalStatus:'NOT_EXPOSED',operandReasonStatus:'NOT_EXPOSED'});
const ref=()=>({present:false});
const relation=()=>({createReturnStatus:'AVAILABLE',lastCreateInvocationId:'compute:7:1:create:1',createdPath:ref(),createdMatchesSinkPath:true,referenceScope:'RAW_RETURNED_VS_CACHED_PATH_REFERENCE_EQUALITY'});
const record=(kind,extra)=>({source:{side:'SERVER'},observationId:'obs:compute:'+kind,gameTime:100,payload:{schema:'kneekura.original-decision-event/v1',semantics:kind.endsWith('CHECKPOINT')?'ORIGINAL_FIELD_WRITE_CHECKPOINT_ONLY':'ORIGINAL_INVOCATION_RETURN_ONLY',targetRevision:7,burstId:'burst:7:100',eventIndex:1,kind,data:{...common(),...extra},observerCostNanos:1,observerCostScope:'BUILD_AND_FIRST_BYTE_CHECK_EXCLUDES_FINAL_ENCODING_WRITER'}});
const compute=()=>record('BRAIN_PATH_COMPUTE_RETURN',{result:false,resultScope:'ORIGINAL_PRIVATE_COMPUTE_BOOLEAN_NOT_CAN_REACH_ADOPTION_OR_ARRIVAL',sinkPath:ref(),navigationPath:ref(),...relation()});
const create=()=>record('BRAIN_PATH_CREATE_RETURN',{createInvocationId:'compute:7:1:create:1',createSite:'INITIAL',arguments:{kind:'BLOCK_POS_I',accuracy:0,present:true,className:'net.minecraft.core.BlockPos',positionStatus:'AVAILABLE',x:1,y:0,z:0},returnedPath:ref(),navigationPath:ref(),returnedMatchesNavigationPath:true,capturedFinderInvocationIds:['compute:7:1:create:1:finder:1'],capturedFinderInvocationsTruncated:false,searchScope:'CAPTURED_ORIGINAL_BASE_NAVIGATION_FINDER_CALLS_ONLY_EMPTY_IS_NOT_NO_SEARCH_PROOF',returnScope:'ORIGINAL_CREATE_PATH_NORMAL_RETURN_NOT_ADOPTION_OR_ARRIVAL'});
const write=()=>record('BRAIN_PATH_COMPUTE_PATH_WRITE_CHECKPOINT',{writeSite:'INITIAL',writeScope:'AFTER_ORIGINAL_SINK_PATH_PUTFIELD_NOT_NAVIGATION_ADOPTION',sinkPath:ref(),...relation()});
const finder=()=>record('BRAIN_PATH_FINDER_RETURN',{createInvocationId:'compute:7:1:create:1',createSite:'INITIAL',finderInvocationId:'compute:7:1:create:1:finder:1',finderClass:'net.minecraft.world.level.pathfinder.PathFinder',targetSetClass:'java.util.HashSet',targetContentsStatus:'NOT_EXPOSED',followRange:32,accuracy:0,maxVisitedNodesMultiplier:1,returnedPath:ref(),searchIdStatus:'AVAILABLE',searchId:'search:7:1',returnScope:'ORIGINAL_NAVIGATION_SOURCE_FINDER_NORMAL_RETURN_NOT_ADOPTION_OR_ARRIVAL'});
test('direct compute/create/Finder returns and original field write remain partial without selection/adoption/arrival',()=>{
 const records=[finder(),create(),write(),compute()];assert.ok(records.every(validOriginalDecisionEvent));const stages={},capabilities={},timeline=[];appendOriginalDecisionEvents(records,stages,capabilities,timeline);assert.equal(stages.EVALUATION.facts.length,3);assert.equal(stages.EXECUTION.facts.length,1);assert.equal(capabilities.brain_navigation.status,'PARTIAL');for(const s of ['CANDIDATE','SELECTION','RESULT'])assert.equal(stages[s],undefined);
});
test('reject wrong scope/revision/cap, fake boolean reasons and conflicting reference equality',()=>{
 for(const mutate of [d=>d.result='true',d=>d.arrivalStatus='AVAILABLE',d=>d.resultScope='ARRIVED',d=>d.canReach=true,d=>d.computeInvocationId='compute:8:1',d=>d.computeInvocationId='compute:7:257',d=>d.lastCreateInvocationId='compute:7:2:create:1',d=>d.createdMatchesSinkPath=false,d=>d.enclosingSinkInvocationStatus='AVAILABLE',d=>d.enclosingTickStopInvocationId='tick-stop:7:1']){const r=compute();mutate(r.payload.data);assert.equal(validOriginalDecisionEvent(r),false);}
 const r=write();r.payload.semantics='ORIGINAL_INVOCATION_RETURN_ONLY';assert.equal(validOriginalDecisionEvent(r),false);
});
test('empty direct capture and capped unknown IDs never imply no search or fabricate prior create relation',()=>{
 const r=create();r.payload.data.capturedFinderInvocationIds=[];assert.equal(validOriginalDecisionEvent(r),true);delete r.payload.data.instanceIdentity;r.payload.data.instanceIdentityStatus='NOT_EXPOSED';assert.equal(validOriginalDecisionEvent(r),true);
 const c=compute();for(const k of ['lastCreateInvocationId','createdPath','createdMatchesSinkPath'])delete c.payload.data[k];c.payload.data.createReturnStatus='NOT_CAPTURED';assert.equal(validOriginalDecisionEvent(c),true);
 for(const ids of [['compute:7:1:create:1:finder:2','compute:7:1:create:1:finder:1'],['compute:7:1:create:1:finder:1','compute:7:1:create:1:finder:1'],['compute:7:1:create:2:finder:1'],['compute:7:1:create:1:finder:9']]){r.payload.data.capturedFinderInvocationIds=ids;assert.equal(validOriginalDecisionEvent(r),false);}
});
test('strict actual passed operands allow custom and nonfinite unknowns without replay',()=>{
 const r=create();r.payload.data.createSite='FALLBACK';r.payload.data.arguments={kind:'DDD_I',accuracy:0,xStatus:'NOT_EXPOSED',y:2,zStatus:'NOT_EXPOSED'};assert.equal(validOriginalDecisionEvent(r),true);r.payload.data.arguments.x=NaN;assert.equal(validOriginalDecisionEvent(r),false);
 const c=create();c.payload.data.arguments={kind:'BLOCK_POS_I',accuracy:0,present:true,className:'custom.Position',positionStatus:'NOT_EXPOSED'};assert.equal(validOriginalDecisionEvent(c),true);c.payload.data.arguments.x=1;assert.equal(validOriginalDecisionEvent(c),false);
 const f=finder();delete f.payload.data.searchId;f.payload.data.searchIdStatus='NOT_CAPTURED';assert.equal(validOriginalDecisionEvent(f),true);f.payload.data.searchId='search:7:1';assert.equal(validOriginalDecisionEvent(f),false);
});
test('actual enclosing scopes and Finder children use bounded source IDs only',()=>{
 const r=compute();Object.assign(r.payload.data,{enclosingSinkInvocationStatus:'AVAILABLE',enclosingSinkInvocationId:'sink:7:1',enclosingTickStopInvocationStatus:'AVAILABLE',enclosingTickStopInvocationId:'tick-stop:7:2'});assert.equal(validOriginalDecisionEvent(r),true);r.payload.data.parentScope='TIME_NEARBY_IS_CAUSE';assert.equal(validOriginalDecisionEvent(r),false);
 const c=create();c.payload.data.capturedFinderInvocationIds=Array.from({length:8},(_,i)=>'compute:7:1:create:1:finder:'+(i+1));c.payload.data.capturedFinderInvocationsTruncated=true;assert.equal(validOriginalDecisionEvent(c),true);c.payload.data.capturedFinderInvocationIds.pop();assert.equal(validOriginalDecisionEvent(c),false);
});
