package com.github.tartaricacid.touhoulittlemaid.sim.debug;

import com.google.common.collect.ImmutableList;
import com.google.gson.JsonObject;
import com.mojang.datafixers.util.Pair;
import net.minecraft.world.entity.Mob;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.entity.ai.Brain;
import net.minecraft.world.entity.ai.memory.MemoryModuleType;
import net.minecraft.world.entity.ai.memory.MemoryStatus;
import net.minecraft.world.entity.schedule.Activity;
import org.objectweb.asm.*;
import org.objectweb.asm.Type;
import java.lang.reflect.*;
import java.util.*;
import java.util.concurrent.atomic.AtomicLong;
import java.util.concurrent.atomic.AtomicReference;
import java.util.function.BooleanSupplier;

/** Original private predicate and both caller bytecodes; source delegates only, no query replay. */
public final class KneekuraDebugActivityRequirementSelfTest {
    private static final class Subject extends Mob {
        private Subject(){super(null,null);}
        @Override public Brain<?> getBrain(){throw new AssertionError("OWNER_GETTER_REPLAY");}
    }
    private static final class ProbeBrain extends Brain<LivingEntity> {
        int checks;Boolean forced;Runnable duringCheck,update;RuntimeException failure;
        ProbeBrain(){super(List.of(MemoryModuleType.PATH,MemoryModuleType.WALK_TARGET),List.of(),ImmutableList.of(),()->null);}
        @Override public boolean checkMemory(MemoryModuleType<?> module,MemoryStatus status){checks++;order.add("check:"+status);if(duringCheck!=null)duringCheck.run();if(failure!=null)throw failure;return forced!=null?forced:super.checkMemory(module,status);}
        @Override public void updateActivityFromSchedule(long day,long game){update.run();}
    }
    private static final class Requirements extends LinkedHashMap<Activity,Set<Pair<MemoryModuleType<?>,MemoryStatus>>> {
        int containsCalls,getCalls;RuntimeException failure;Runnable during;
        @Override public boolean containsKey(Object requested){containsCalls++;order.add("contains");if(during!=null)during.run();if(failure!=null)throw failure;return super.containsKey(requested);}
        @Override public Set<Pair<MemoryModuleType<?>,MemoryStatus>> get(Object requested){getCalls++;order.add("get");return super.get(requested);}
    }
    private static final List<String> order=new ArrayList<>();
    private static void require(boolean ok,String message){if(!ok)throw new AssertionError(message);}
    private static Object read(Object owner,Class<?> base,String name){try{return KneekuraDebugDecisionSnapshot.read(base,name,owner);}catch(ReflectiveOperationException e){throw new AssertionError(e);}}
    private static void field(Object owner,Class<?> base,String name,Object value){try{var f=base.getDeclaredField(name);f.setAccessible(true);f.set(owner,value);}catch(ReflectiveOperationException e){throw new AssertionError(e);}}
    private static Object call(Method m,Object owner,Object... args){try{return m.invoke(owner,args);}catch(InvocationTargetException e){if(e.getCause() instanceof RuntimeException r)throw r;if(e.getCause() instanceof Error r)throw r;throw new AssertionError(e);}catch(ReflectiveOperationException e){throw new AssertionError(e);}}
    public static Map<?,?> requirements(Brain<?> brain){return (Map<?,?>)read(brain,Brain.class,"activityRequirements");}
    public static boolean sourceContains(Map<?,?> map,Object key,Brain<?> brain,Activity requested){try{return (Boolean)call(KneekuraDebugDecisionHooks.class.getDeclaredMethod("originalActivityRequirementContains",Brain.class,Map.class,Object.class,Activity.class),null,brain,map,key,requested);}catch(NoSuchMethodException absent){return map.containsKey(key);}}
    public static boolean sourceCheck(Brain<?> brain,MemoryModuleType<?> module,MemoryStatus status,Activity requested){try{return (Boolean)call(KneekuraDebugDecisionHooks.class.getDeclaredMethod("originalActivityRequirementCheck",Brain.class,MemoryModuleType.class,MemoryStatus.class,Activity.class),null,brain,module,status,requested);}catch(NoSuchMethodException absent){return brain.checkMemory(module,status);}}
    public static boolean sourceRequirement(Brain<?> brain,Activity requested,String site){BooleanSupplier body=()->(Boolean)call(predicate,null,brain,requested);try{return (Boolean)call(KneekuraDebugDecisionHooks.class.getDeclaredMethod("originalActivityRequirement",Brain.class,Activity.class,String.class,BooleanSupplier.class),null,brain,requested,site,body);}catch(NoSuchMethodException absent){return body.getAsBoolean();}}
    public static void sourceSetter(Brain<?> brain,Activity requested){call(setter,brain,requested);}
    private static Method predicate,ifPossible,firstValid,original,setter;
    private static void fixtures()throws Exception {
        String brain=Type.getInternalName(Brain.class),test=Type.getInternalName(KneekuraDebugActivityRequirementSelfTest.class),name=test+"$ActualRequirementFixture";
        var w=new ClassWriter(ClassWriter.COMPUTE_FRAMES|ClassWriter.COMPUTE_MAXS);w.visit(Opcodes.V17,Opcodes.ACC_PUBLIC,name,null,"java/lang/Object",null);int[] counts=new int[5];
        try(var bytes=Brain.class.getResourceAsStream("Brain.class")){new ClassReader(bytes).accept(new ClassVisitor(Opcodes.ASM9){
            @Override public MethodVisitor visitMethod(int a,String n,String desc,String sig,String[] ex){if(!Set.of("activityRequirementsAreMet","setActiveActivityIfPossible","setActiveActivityToFirstValid").contains(n))return null;counts[0]++;boolean pred=n.equals("activityRequirementsAreMet");return new MethodVisitor(Opcodes.ASM9,w.visitMethod(Opcodes.ACC_PUBLIC|Opcodes.ACC_STATIC,n,"(L"+brain+";"+desc.substring(1),null,ex)){
                @Override public void visitFieldInsn(int op,String owner,String f,String d){if(pred&&owner.equals(brain)&&op==Opcodes.GETFIELD){require(f.equals("activityRequirements"),"exact private source field accessor");counts[1]++;super.visitMethodInsn(Opcodes.INVOKESTATIC,test,"requirements","(L"+brain+";)Ljava/util/Map;",false);return;}super.visitFieldInsn(op,owner,f,d);}
                @Override public void visitMethodInsn(int op,String owner,String method,String d,boolean itf){
                    if(pred&&owner.equals("java/util/Map")&&method.equals("containsKey")){counts[2]++;super.visitVarInsn(Opcodes.ALOAD,0);super.visitVarInsn(Opcodes.ALOAD,1);super.visitMethodInsn(Opcodes.INVOKESTATIC,test,"sourceContains","(Ljava/util/Map;Ljava/lang/Object;L"+brain+";Lnet/minecraft/world/entity/schedule/Activity;)Z",false);return;}
                    if(pred&&owner.equals(brain)&&method.equals("checkMemory")){counts[3]++;super.visitVarInsn(Opcodes.ALOAD,1);super.visitMethodInsn(Opcodes.INVOKESTATIC,test,"sourceCheck","(L"+brain+";Lnet/minecraft/world/entity/ai/memory/MemoryModuleType;Lnet/minecraft/world/entity/ai/memory/MemoryStatus;Lnet/minecraft/world/entity/schedule/Activity;)Z",false);return;}
                    if(!pred&&owner.equals(brain)&&method.equals("activityRequirementsAreMet")){counts[4]++;super.visitLdcInsn(n.equals("setActiveActivityIfPossible")?"IF_POSSIBLE":"FIRST_VALID");super.visitMethodInsn(Opcodes.INVOKESTATIC,test,"sourceRequirement","(L"+brain+";Lnet/minecraft/world/entity/schedule/Activity;Ljava/lang/String;)Z",false);return;}
                    if(!pred&&owner.equals(brain)&&method.equals("setActiveActivity")){super.visitMethodInsn(Opcodes.INVOKESTATIC,test,"sourceSetter","(L"+brain+";Lnet/minecraft/world/entity/schedule/Activity;)V",false);return;}
                    super.visitMethodInsn(op,owner,method,d,itf);
                }
            };}
        },ClassReader.SKIP_FRAMES);}require(Arrays.equals(counts,new int[]{3,2,1,1,2}),"actual private predicate/two callers/source delegates only");w.visitEnd();byte[] bytes=w.toByteArray();class Loader extends ClassLoader{Loader(){super(KneekuraDebugActivityRequirementSelfTest.class.getClassLoader());}Class<?> define(){return defineClass(name.replace('/','.'),bytes,0,bytes.length);}}var c=new Loader().define();predicate=c.getMethod("activityRequirementsAreMet",Brain.class,Activity.class);ifPossible=c.getMethod("setActiveActivityIfPossible",Brain.class,Activity.class);firstValid=c.getMethod("setActiveActivityToFirstValid",Brain.class,List.class);original=Brain.class.getDeclaredMethod("activityRequirementsAreMet",Activity.class);original.setAccessible(true);setter=Brain.class.getDeclaredMethod("setActiveActivity",Activity.class);setter.setAccessible(true);
    }
    private static List<JsonObject> received(List<JsonObject> rows){return rows.stream().filter(x->x.get("kind").getAsString().equals("BRAIN_ACTIVITY_REQUIREMENT_CHECKS_RETURN")).toList();}
    private static KneekuraDebugDecisionHooks.Session install(Subject owner,Set<String> channels,int events,int bytes,AtomicReference<KneekuraDebugDecisionBurstBudget.Context> context,AtomicLong time,List<JsonObject> rows)throws Exception {
        var snapshot=new KneekuraDebugDecisionSnapshot();snapshot.reset(context.get().selectionRevision());var s=new KneekuraDebugDecisionHooks.Session(owner,null,null,snapshot,new KneekuraDebugDecisionBurstBudget(context.get(),100,100,events,bytes),8,channels,context::get,time::get,(method,row)->rows.add(row));KneekuraDebugDecisionHooks.install(s);return s;
    }
    private static boolean observed(ProbeBrain brain,Activity activity,String site){boolean[] result={false};brain.update=()->result[0]=sourceRequirement(brain,activity,site);KneekuraDebugDecisionHooks.originalActivityUpdate(brain,100,100);return result[0];}
    private static int emitted;private static void emit(List<JsonObject> rows){for(var row:received(rows)){System.out.println("ACTIVITY_REQUIREMENT_INTEROP:"+new com.google.gson.Gson().toJson(row));emitted++;}}

    private static void compiledHandlers()throws Exception {
        String activity="(Lnet/minecraft/world/entity/schedule/Activity;)",source="activityRequirementsAreMet"+activity+"Z",target="Lnet/minecraft/world/entity/ai/Brain;"+source;
        var expected=Map.of("kneekura$requirementIfPossible",new String[]{"setActiveActivityIfPossible"+activity+"V",target,"originalActivityRequirement"},
            "kneekura$requirementFirstValid",new String[]{"setActiveActivityToFirstValid(Ljava/util/List;)V",target,"originalActivityRequirement"},
            "kneekura$requirementContains",new String[]{source,"Ljava/util/Map;containsKey(Ljava/lang/Object;)Z","originalActivityRequirementContains"},
            "kneekura$requirementCheck",new String[]{source,"Lnet/minecraft/world/entity/ai/Brain;checkMemory(Lnet/minecraft/world/entity/ai/memory/MemoryModuleType;Lnet/minecraft/world/entity/ai/memory/MemoryStatus;)Z","originalActivityRequirementCheck"});
        var found=new HashSet<String>();int[] invokers={0},delegates={0};
        try(var bytes=KneekuraDebugActivityRequirementSelfTest.class.getResourceAsStream("decisionmixin/KneekuraDebugBrainDecisionMixin.class")){new ClassReader(bytes).accept(new ClassVisitor(Opcodes.ASM9){
            @Override public MethodVisitor visitMethod(int a,String n,String d,String sig,String[] ex){
                if(n.equals("kneekura$invokeActivityRequirement")){require((a&Opcodes.ACC_ABSTRACT)!=0&&d.equals(activity+"Z"),"exact private predicate Invoker signature");return new MethodVisitor(Opcodes.ASM9){@Override public AnnotationVisitor visitAnnotation(String desc,boolean visible){if(!desc.equals("Lorg/spongepowered/asm/mixin/gen/Invoker;"))return null;return new AnnotationVisitor(Opcodes.ASM9){@Override public void visit(String key,Object v){if(key.equals("value")){require(v.equals("activityRequirementsAreMet"),"original private predicate target");invokers[0]++;}if(key.equals("remap"))require(v.equals(false),"pinned Invoker");}};}};}
                if(n.startsWith("lambda$kneekura$requirementIfPossible$")||n.startsWith("lambda$kneekura$requirementFirstValid$"))return new MethodVisitor(Opcodes.ASM9){@Override public void visitMethodInsn(int op,String owner,String name,String desc,boolean itf){require(op==Opcodes.INVOKEVIRTUAL&&owner.endsWith("/KneekuraDebugBrainDecisionMixin")&&name.equals("kneekura$invokeActivityRequirement")&&desc.equals(activity+"Z"),"one original private predicate delegate per caller");delegates[0]++;}};
                var spec=expected.get(n);if(spec==null)return null;
                String brain="Lnet/minecraft/world/entity/ai/Brain;",act="Lnet/minecraft/world/entity/schedule/Activity;";
                String handler=n.equals("kneekura$requirementContains")?"(Ljava/util/Map;Ljava/lang/Object;"+act+")Z":n.equals("kneekura$requirementCheck")?"("+brain+"Lnet/minecraft/world/entity/ai/memory/MemoryModuleType;Lnet/minecraft/world/entity/ai/memory/MemoryStatus;"+act+")Z":"("+brain+act+")Z";
                require(d.equals(handler),"exact source argument handler descriptor "+n);found.add(n);int[] counts=new int[4];return new MethodVisitor(Opcodes.ASM9){
                    private AnnotationVisitor annotation(){return new AnnotationVisitor(Opcodes.ASM9){@Override public void visit(String key,Object v){if(key.equals("require")){require(v.equals(1),"mandatory source Redirect");counts[2]++;}if(key.equals("target")){require(v.equals(spec[1]),"exact source target");counts[1]++;}}
                        @Override public AnnotationVisitor visitArray(String key){if(key.equals("method"))return new AnnotationVisitor(Opcodes.ASM9){@Override public void visit(String key,Object v){require(v.equals(spec[0]),"exact source caller/loop selector");counts[0]++;}};return annotation();}
                        @Override public AnnotationVisitor visitAnnotation(String key,String desc){return annotation();}};}
                    @Override public AnnotationVisitor visitAnnotation(String desc,boolean visible){return desc.equals("Lorg/spongepowered/asm/mixin/injection/Redirect;")?annotation():null;}
                    @Override public void visitMethodInsn(int op,String owner,String name,String desc,boolean itf){require(op==Opcodes.INVOKESTATIC&&owner.endsWith("/KneekuraDebugDecisionHooks")&&name.equals(spec[2]),"single production delegate");counts[3]++;}
                    @Override public void visitEnd(){require(Arrays.equals(counts,new int[]{1,1,1,1}),"one mandatory source Redirect "+n);}
                };}
        },0);}require(found.equals(expected.keySet())&&invokers[0]==1&&delegates[0]==2,"four exact Redirects/one private Invoker/two original caller delegates");
        var calls=new HashMap<String,Integer>();try(var bytes=KneekuraDebugDecisionHooks.class.getResourceAsStream("KneekuraDebugDecisionHooks.class")){new ClassReader(bytes).accept(new ClassVisitor(Opcodes.ASM9){@Override public MethodVisitor visitMethod(int a,String n,String d,String sig,String[] ex){if(!Set.of("originalActivityRequirementContains","originalActivityRequirementCheck").contains(n))return null;return new MethodVisitor(Opcodes.ASM9){@Override public void visitMethodInsn(int op,String owner,String name,String desc,boolean itf){if(owner.equals("java/util/Map")||owner.equals("net/minecraft/world/entity/ai/Brain")){require(op==(owner.equals("java/util/Map")?Opcodes.INVOKEINTERFACE:Opcodes.INVOKEVIRTUAL),"original dispatch opcode");require(name.equals(n.equals("originalActivityRequirementContains")?"containsKey":"checkMemory"),"only source query delegates");calls.merge(n,1,Integer::sum);}}};}},0);}require(calls.equals(Map.of("originalActivityRequirementContains",2,"originalActivityRequirementCheck",2)),"OFF and observed branches each execute original once");
    }
    public static void main(String[] args)throws Exception {
        net.minecraft.SharedConstants.tryDetectVersion();net.minecraft.server.Bootstrap.bootStrap();var uf=sun.misc.Unsafe.class.getDeclaredField("theUnsafe");uf.setAccessible(true);var owner=(Subject)((sun.misc.Unsafe)uf.get(null)).allocateInstance(Subject.class);var brain=new ProbeBrain();field(owner,LivingEntity.class,"brain",brain);var map=new Requirements();field(brain,Brain.class,"activityRequirements",map);fixtures();
        var context=new AtomicReference<>(new KneekuraDebugDecisionBurstBudget.Context("session","run","snapshot",1,0,7,"11111111-2222-3333-4444-555555555555","minecraft:overworld"));var time=new AtomicLong(100);var rows=new ArrayList<JsonObject>();
        boolean baseline=(Boolean)call(original,brain,Activity.REST);var baselineOrder=List.copyOf(order);require(!baseline&&map.containsCalls==1&&map.getCalls==0&&brain.checks==0,"unregistered Activity original false no get/check");order.clear();map.containsCalls=map.getCalls=0;install(owner,Set.of("brain_activity"),256,524288,context,time,rows);require(observed(brain,Activity.REST,"IF_POSSIBLE")==baseline&&order.equals(baselineOrder)&&map.containsCalls==1&&map.getCalls==0,"original missing-map order/calls preserved");require(received(rows).size()==1,"missing actual Activity requirement source receipt");emit(rows);
        map.put(Activity.REST,new LinkedHashSet<>());rows.clear();install(owner,Set.of("brain_activity"),256,524288,context,time,rows);require(observed(brain,Activity.REST,"IF_POSSIBLE"),"registered empty set original true");require(received(rows).get(0).getAsJsonObject("data").getAsJsonArray("checks").isEmpty(),"empty source set not missing entry or fabricated checks");emit(rows);
        var entries=new LinkedHashSet<Pair<MemoryModuleType<?>,MemoryStatus>>();entries.add(Pair.of(MemoryModuleType.PATH,MemoryStatus.REGISTERED));entries.add(Pair.of(MemoryModuleType.WALK_TARGET,MemoryStatus.VALUE_PRESENT));entries.add(Pair.of(MemoryModuleType.PATH,MemoryStatus.VALUE_PRESENT));map.put(Activity.REST,entries);brain.checks=map.containsCalls=map.getCalls=0;order.clear();baseline=(Boolean)call(original,brain,Activity.REST);baselineOrder=List.copyOf(order);int baselineChecks=brain.checks;brain.checks=map.containsCalls=map.getCalls=0;order.clear();rows.clear();install(owner,Set.of("brain_activity"),256,524288,context,time,rows);require(!observed(brain,Activity.REST,"IF_POSSIBLE")&&baselineChecks==2&&brain.checks==2&&order.equals(baselineOrder),"actual first false short circuit no getter/query/Pair replay");emit(rows);
        brain.forced=true;rows.clear();install(owner,Set.of("brain_activity"),256,524288,context,time,rows);require(observed(brain,Activity.REST,"IF_POSSIBLE"),"virtual custom true preserved independently of cached slots");emit(rows);
        rows.clear();install(owner,Set.of("brain_activity"),256,524288,context,time,rows);brain.update=()->call(firstValid,null,brain,List.of(Activity.IDLE,Activity.REST,Activity.FIGHT));KneekuraDebugDecisionHooks.originalActivityUpdate(brain,100,100);require(received(rows).size()==2&&received(rows).stream().allMatch(x->x.getAsJsonObject("data").get("callerSite").getAsString().equals("FIRST_VALID")),"actual first-valid caller stops after first true; tail not observed");emit(rows);
        rows.clear();install(owner,Set.of("brain_activity"),256,524288,context,time,rows);brain.update=()->call(ifPossible,null,brain,Activity.REST);KneekuraDebugDecisionHooks.originalActivityUpdate(brain,100,100);require(received(rows).size()==1&&received(rows).get(0).getAsJsonObject("data").get("callerSite").getAsString().equals("IF_POSSIBLE"),"actual if-possible source caller");emit(rows);
        for(int mode=0;mode<2;mode++){var unknown=new MemoryModuleType<Object>(Optional.empty());map.put(Activity.REST,new LinkedHashSet<>(List.of(Pair.of(mode==0?unknown:MemoryModuleType.PATH,mode==0?MemoryStatus.REGISTERED:null))));rows.clear();install(owner,Set.of("brain_activity"),256,524288,context,time,rows);require(observed(brain,Activity.REST,"IF_POSSIBLE"),"custom virtual true with unknown/null operand unchanged");emit(rows);}
        for(Activity requested:Arrays.asList(Activity.HIDE,null)){map.put(requested,new LinkedHashSet<>());rows.clear();install(owner,Set.of("brain_activity"),256,524288,context,time,rows);require(observed(brain,requested,"IF_POSSIBLE"),"unknown/null Activity normal empty-set true");require(received(rows).get(0).getAsJsonObject("data").get("requestedActivityStatus").getAsString().equals("NOT_EXPOSED"),"unknown Activity not registry replay");emit(rows);}
        var many=new LinkedHashSet<Pair<MemoryModuleType<?>,MemoryStatus>>();for(int i=0;i<9;i++)many.add(Pair.of(new MemoryModuleType<Object>(Optional.empty()),MemoryStatus.REGISTERED));map.put(Activity.REST,many);rows.clear();brain.checks=0;install(owner,Set.of("brain_activity"),256,524288,context,time,rows);require(observed(brain,Activity.REST,"IF_POSSIBLE")&&brain.checks==9,"all nine original virtual calls still execute");var d=received(rows).get(0).getAsJsonObject("data");require(d.getAsJsonArray("checks").size()==8&&d.get("checksTruncated").getAsBoolean(),"actual ninth normal-return tail with prefix eight");emit(rows);
        map.put(Activity.REST,new LinkedHashSet<>(List.of(Pair.of(MemoryModuleType.PATH,MemoryStatus.REGISTERED))));rows.clear();brain.checks=0;install(owner,Set.of("brain_activity"),256,524288,context,time,rows);brain.duringCheck=()->{brain.duringCheck=null;sourceCheck(brain,MemoryModuleType.WALK_TARGET,MemoryStatus.VALUE_PRESENT,Activity.REST);};require(observed(brain,Activity.REST,"IF_POSSIBLE")&&brain.checks==2,"arbitrary nested check executes exactly once");require(received(rows).get(0).getAsJsonObject("data").getAsJsonArray("checks").size()==1,"callback is not original predicate prefix evidence");emit(rows);
        rows.clear();install(owner,Set.of("brain_activity"),256,524288,context,time,rows);brain.duringCheck=()->{brain.duringCheck=null;sourceRequirement(brain,Activity.REST,"FIRST_VALID");};require(observed(brain,Activity.REST,"IF_POSSIBLE")&&received(rows).size()==2,"genuine nested private predicate scopes recorded separately");require(received(rows).get(0).getAsJsonObject("data").get("requirementInvocationId").getAsString().equals("activity-requirement:7:2")&&received(rows).get(1).getAsJsonObject("data").get("requirementInvocationId").getAsString().equals("activity-requirement:7:1"),"nested normal completion/source ID order");emit(rows);
        var sentinel=new IllegalStateException("ORIGINAL_PREDICATE_EXCEPTION");for(int mode=0;mode<2;mode++){rows.clear();var session=install(owner,Set.of("brain_activity"),256,524288,context,time,rows);if(mode==0)map.failure=sentinel;else brain.failure=sentinel;try{observed(brain,Activity.REST,"IF_POSSIBLE");throw new AssertionError("expected original exception");}catch(IllegalStateException e){require(e==sentinel,"original exception identity unchanged");}finally{map.failure=brain.failure=null;}require(received(rows).isEmpty()&&read(session,KneekuraDebugDecisionHooks.Session.class,"activityRequirementFrame")==null,"exception has no fabricated normal receipt, frame cleaned");}
        map.put(Activity.REST,null);rows.clear();install(owner,Set.of("brain_activity"),256,524288,context,time,rows);try{observed(brain,Activity.REST,"IF_POSSIBLE");throw new AssertionError("original null Set must throw");}catch(NullPointerException originalNull){require(received(rows).isEmpty(),"original Map.get null exception not hidden");}map.put(Activity.REST,new LinkedHashSet<>(List.of(Pair.of(MemoryModuleType.PATH,MemoryStatus.REGISTERED))));
        rows.clear();install(owner,Set.of("brain_activity"),256,524288,context,time,rows);brain.duringCheck=()->{brain.duringCheck=null;field(brain,Brain.class,"activityRequirements",new Requirements());};require(observed(brain,Activity.REST,"IF_POSSIBLE")&&received(rows).isEmpty(),"changed raw requirement Map suppresses whole new summary");field(brain,Brain.class,"activityRequirements",map);
        for(int mode=0;mode<5;mode++){rows.clear();time.set(100);var session=install(owner,Set.of("brain_activity"),256,524288,context,time,rows);int selected=mode;brain.duringCheck=()->{brain.duringCheck=null;switch(selected){case 0->time.set(201);case 1->field(owner,LivingEntity.class,"brain",new ProbeBrain());case 2->KneekuraDebugDecisionHooks.clear("SOURCE_CLEAR");case 3->{try{install(owner,Set.of("brain_activity"),256,524288,context,time,rows);}catch(Exception e){throw new AssertionError(e);}}case 4->session.budget().close("SOURCE_CLOSE");}};require(observed(brain,Activity.REST,"IF_POSSIBLE")&&received(rows).isEmpty(),"gate suppresses late receipt without changing original boolean mode="+mode);field(owner,LivingEntity.class,"brain",brain);time.set(100);KneekuraDebugDecisionHooks.clear("DONE");}
        rows.clear();KneekuraDebugDecisionHooks.clear("OFF");int calls=brain.checks;require(observed(brain,Activity.REST,"IF_POSSIBLE")&&brain.checks==calls+1&&rows.isEmpty(),"OFF original once");install(owner,Set.of("brain_navigation"),256,524288,context,time,rows);require(observed(brain,Activity.REST,"IF_POSSIBLE")&&rows.isEmpty(),"other channel remains OFF");
        rows.clear();install(owner,Set.of("brain_activity"),256,524288,context,time,rows);var failure=new AtomicReference<Throwable>();var thread=new Thread(()->{try{require(observed(brain,Activity.REST,"IF_POSSIBLE"),"wrong thread original boolean");}catch(Throwable e){failure.set(e);}});thread.start();thread.join();require(failure.get()==null&&rows.isEmpty(),"wrong thread executes original with no observation");
        for(int mode=0;mode<2;mode++){rows.clear();install(owner,Set.of("brain_activity"),mode==0?1:256,mode==0?524288:1,context,time,rows);require(observed(brain,Activity.REST,"IF_POSSIBLE"),"budget does not alter original result");require(mode==0?rows.size()==1&&received(rows).size()==1:rows.isEmpty(),"event/byte finite limits");}
        rows.clear();var session=install(owner,Set.of("brain_activity"),256,524288,context,time,rows);field(session,KneekuraDebugDecisionHooks.Session.class,"nextActivityRequirement",255);observed(brain,Activity.REST,"IF_POSSIBLE");observed(brain,Activity.REST,"IF_POSSIBLE");require(received(rows).size()==1&&received(rows).get(0).getAsJsonObject("data").get("requirementInvocationId").getAsString().equals("activity-requirement:7:256"),"independent requirement ID256 cap");emit(rows);
        rows.clear();session=install(owner,Set.of("brain_activity"),256,524288,context,time,rows);field(session,KneekuraDebugDecisionHooks.Session.class,"activityRequirementDepth",8);require(observed(brain,Activity.REST,"IF_POSSIBLE")&&received(rows).isEmpty(),"ninth depth no new receipt but original executes");
        rows.clear();session=install(owner,Set.of("brain_activity"),256,524288,context,time,rows);var identities=(Map<Object,String>)read(session,KneekuraDebugDecisionHooks.Session.class,"identities");for(int i=0;i<128;i++)identities.put(new Object(),"synthetic:"+i);observed(brain,Activity.REST,"IF_POSSIBLE");require(received(rows).get(0).getAsJsonObject("data").get("instanceIdentityStatus").getAsString().equals("NOT_EXPOSED"),"component128 cap remains unknown");emit(rows);

        for(int mode=0;mode<6;mode++){rows.clear();var old=context.get();install(owner,Set.of("brain_activity"),256,524288,context,time,rows);int selected=mode;brain.duringCheck=()->{brain.duringCheck=null;context.set(new KneekuraDebugDecisionBurstBudget.Context(selected==0?"other":old.sessionId(),selected==1?"other":old.runId(),selected==2?"other":old.snapshotId(),selected==3?2:old.processEpoch(),selected==4?1:old.arenaEpoch(),selected==5?8:old.selectionRevision(),old.subjectUuid(),old.dimension()));};require(observed(brain,Activity.REST,"IF_POSSIBLE")&&received(rows).isEmpty(),"changed original context suppresses late receipt mode="+mode);context.set(old);}
        rows.clear();var snapshot=new KneekuraDebugDecisionSnapshot();snapshot.reset(7);session=new KneekuraDebugDecisionHooks.Session(owner,null,null,snapshot,new KneekuraDebugDecisionBurstBudget(context.get(),100,100,256,524288),8,Set.of("brain_activity"),context::get,time::get,(method,row)->{throw new java.io.IOException("WRITER_FAILURE");});KneekuraDebugDecisionHooks.install(session);require(observed(brain,Activity.REST,"IF_POSSIBLE")&&read(session,KneekuraDebugDecisionHooks.Session.class,"activityRequirementFrame")==null,"writer failure preserves original boolean and cleans frame");
        compiledHandlers();
        KneekuraDebugDecisionHooks.clear("DONE");System.out.println("Activity requirement genuine predicate and both caller fixtures passed; Gson cases="+emitted);
    }
}
