package com.github.tartaricacid.touhoulittlemaid.sim.debug;

import com.google.common.collect.ImmutableList;
import com.google.gson.JsonObject;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.entity.Mob;
import net.minecraft.world.entity.ai.Brain;
import net.minecraft.world.entity.ai.behavior.BehaviorControl;
import net.minecraft.world.entity.ai.behavior.MoveToTargetSink;
import net.minecraft.world.entity.ai.memory.MemoryModuleType;
import net.minecraft.world.entity.ai.memory.MemoryStatus;
import net.minecraft.world.entity.ai.navigation.PathNavigation;
import net.minecraft.world.entity.schedule.Activity;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.pathfinder.PathFinder;
import net.minecraft.world.phys.Vec3;
import org.objectweb.asm.*;
import org.objectweb.asm.Type;
import java.lang.reflect.*;
import java.util.*;
import java.util.concurrent.atomic.AtomicLong;
import java.util.concurrent.atomic.AtomicReference;
import java.util.function.BooleanSupplier;

/** Genuine base checkMemory bytecode, original casts/branches and normal return sites retained. */
public final class KneekuraDebugBrainMemorySourceSelfTest {
    private static final class Subject extends Mob {private Subject(){super(null,null);}@Override public Brain<?> getBrain(){throw new AssertionError("OWNER_GETTER_REPLAY");}}
    private static final class Navigation extends PathNavigation {
        private Navigation(Mob owner,Level level){super(owner,level);}
        @Override protected PathFinder createPathFinder(int limit){throw new AssertionError("SEARCH_REPLAY");}
        @Override protected Vec3 getTempMobPos(){throw new AssertionError("POSITION_REPLAY");}
        @Override protected boolean canUpdatePath(){throw new AssertionError("UPDATE_REPLAY");}
    }
    private static final class ProbeBrain extends Brain<Mob> {
        int calls;boolean baseline,invert,repeated;Boolean forced;Runnable during,update;
        ProbeBrain(){super(List.of(MemoryModuleType.PATH,MemoryModuleType.WALK_TARGET),List.of(),ImmutableList.of(),()->null);}
        @Override public boolean checkMemory(MemoryModuleType<?> module,MemoryStatus status){calls++;if(during!=null)during.run();if(forced!=null)return forced;boolean result=baseline?super.checkMemory(module,status):(Boolean)call(fixture,null,this,module,status);if(repeated)call(fixture,null,this,module,status);return invert?!result:result;}
        @Override public void updateActivityFromSchedule(long day,long game){update.run();}
    }
    private static final class Slots extends LinkedHashMap<Object,Object> {int gets;Runnable during;RuntimeException failure;@Override public Object get(Object key){gets++;if(during!=null)during.run();if(failure!=null)throw failure;return super.get(key);}}
    private static void require(boolean ok,String message){if(!ok)throw new AssertionError(message);}
    private static Object read(Object owner,Class<?> base,String name){try{return KneekuraDebugDecisionSnapshot.read(base,name,owner);}catch(ReflectiveOperationException e){throw new AssertionError(e);}}
    private static void field(Object owner,Class<?> base,String name,Object value){try{var f=base.getDeclaredField(name);f.setAccessible(true);f.set(owner,value);}catch(ReflectiveOperationException e){throw new AssertionError(e);}}
    private static Object call(Method m,Object owner,Object... args){try{return m.invoke(owner,args);}catch(InvocationTargetException e){if(e.getCause() instanceof RuntimeException r)throw r;if(e.getCause() instanceof Error r)throw r;throw new AssertionError(e);}catch(ReflectiveOperationException e){throw new AssertionError(e);}}
    private static Object hook(String name,Class<?>[] types,Object... args)throws NoSuchMethodException {return call(KneekuraDebugDecisionHooks.class.getDeclaredMethod(name,types),null,args);}
    public static Map<?,?> slots(Brain<?> brain){return (Map<?,?>)read(brain,Brain.class,"memories");}
    public static Object sourceGet(Map<?,?> slots,Object key,Brain<?> brain,MemoryModuleType<?> module,MemoryStatus status){try{return hook("originalMemorySourceGet",new Class<?>[]{Brain.class,Map.class,Object.class,MemoryModuleType.class,MemoryStatus.class},brain,slots,key,module,status);}catch(NoSuchMethodException absent){return slots.get(key);}}
    public static boolean sourcePresence(Optional<?> slot,Brain<?> brain,MemoryModuleType<?> module,MemoryStatus status,String site){try{return (Boolean)hook("originalMemorySourcePresence",new Class<?>[]{Brain.class,Optional.class,MemoryModuleType.class,MemoryStatus.class,String.class},brain,slot,module,status,site);}catch(NoSuchMethodException absent){return slot.isPresent();}}
    public static boolean sourceReturn(boolean result,Brain<?> brain,MemoryModuleType<?> module,MemoryStatus status){try{hook("memorySourceBaseReturn",new Class<?>[]{Brain.class,MemoryModuleType.class,MemoryStatus.class,boolean.class},brain,module,status,result);}catch(NoSuchMethodException absent){}return result;}
    private static Method fixture;
    private static void fixture()throws Exception {
        String brain=Type.getInternalName(Brain.class),test=Type.getInternalName(KneekuraDebugBrainMemorySourceSelfTest.class),name=test+"$ActualBaseFixture";var w=new ClassWriter(ClassWriter.COMPUTE_FRAMES|ClassWriter.COMPUTE_MAXS);w.visit(Opcodes.V17,Opcodes.ACC_PUBLIC,name,null,"java/lang/Object",null);int[] counts=new int[5];
        try(var bytes=Brain.class.getResourceAsStream("Brain.class")){new ClassReader(bytes).accept(new ClassVisitor(Opcodes.ASM9){@Override public MethodVisitor visitMethod(int a,String n,String desc,String sig,String[] ex){if(!n.equals("checkMemory"))return null;counts[0]++;return new MethodVisitor(Opcodes.ASM9,w.visitMethod(Opcodes.ACC_PUBLIC|Opcodes.ACC_STATIC,"check","(L"+brain+";"+desc.substring(1),null,ex)){
            @Override public void visitFieldInsn(int op,String owner,String f,String d){if(op==Opcodes.GETFIELD&&owner.equals(brain)){require(f.equals("memories"),"exact private source field");counts[1]++;super.visitMethodInsn(Opcodes.INVOKESTATIC,test,"slots","(L"+brain+";)Ljava/util/Map;",false);return;}super.visitFieldInsn(op,owner,f,d);}
            private void arguments(){super.visitVarInsn(Opcodes.ALOAD,0);super.visitVarInsn(Opcodes.ALOAD,1);super.visitVarInsn(Opcodes.ALOAD,2);}
            @Override public void visitMethodInsn(int op,String owner,String n,String d,boolean itf){if(owner.equals("java/util/Map")&&n.equals("get")){require(op==Opcodes.INVOKEINTERFACE,"original map delegate opcode");counts[2]++;arguments();super.visitMethodInsn(Opcodes.INVOKESTATIC,test,"sourceGet","(Ljava/util/Map;Ljava/lang/Object;L"+brain+";Lnet/minecraft/world/entity/ai/memory/MemoryModuleType;Lnet/minecraft/world/entity/ai/memory/MemoryStatus;)Ljava/lang/Object;",false);return;}if(owner.equals("java/util/Optional")&&n.equals("isPresent")){require(op==Opcodes.INVOKEVIRTUAL,"original presence delegate opcode");arguments();super.visitLdcInsn(counts[3]++==0?"VALUE_PRESENT":"VALUE_ABSENT");super.visitMethodInsn(Opcodes.INVOKESTATIC,test,"sourcePresence","(Ljava/util/Optional;L"+brain+";Lnet/minecraft/world/entity/ai/memory/MemoryModuleType;Lnet/minecraft/world/entity/ai/memory/MemoryStatus;Ljava/lang/String;)Z",false);return;}super.visitMethodInsn(op,owner,n,d,itf);}
            @Override public void visitInsn(int op){if(op==Opcodes.IRETURN){counts[4]++;arguments();super.visitMethodInsn(Opcodes.INVOKESTATIC,test,"sourceReturn","(ZL"+brain+";Lnet/minecraft/world/entity/ai/memory/MemoryModuleType;Lnet/minecraft/world/entity/ai/memory/MemoryStatus;)Z",false);}super.visitInsn(op);}
        };}},ClassReader.SKIP_FRAMES);}require(Arrays.equals(counts,new int[]{1,1,1,2,2}),"genuine base method/field/get/two presence/two return sites");w.visitEnd();byte[] bytes=w.toByteArray();class Loader extends ClassLoader{Loader(){super(KneekuraDebugBrainMemorySourceSelfTest.class.getClassLoader());}Class<?> define(){return defineClass(name.replace('/','.'),bytes,0,bytes.length);}}fixture=new Loader().define().getMethod("check",Brain.class,MemoryModuleType.class,MemoryStatus.class);
    }
    private static List<JsonObject> received(List<JsonObject> rows){return rows.stream().filter(x->x.get("kind").getAsString().endsWith("MEMORY_SOURCE_RETURN")).toList();}
    private static KneekuraDebugDecisionHooks.Session install(Subject owner,Set<String> channels,int events,int bytes,AtomicReference<KneekuraDebugDecisionBurstBudget.Context> context,AtomicLong time,List<JsonObject> rows)throws Exception {var snapshot=new KneekuraDebugDecisionSnapshot();snapshot.reset(context.get().selectionRevision());var s=new KneekuraDebugDecisionHooks.Session(owner,null,null,snapshot,new KneekuraDebugDecisionBurstBudget(context.get(),100,100,events,bytes),8,channels,context::get,time::get,(method,row)->rows.add(row));KneekuraDebugDecisionHooks.install(s);return s;}
    private static boolean observed(boolean activity,ProbeBrain brain,MoveToTargetSink behavior,Subject owner,MemoryModuleType<?> module,MemoryStatus status)throws Exception {
        if(activity){boolean[] result={false};brain.update=()->result[0]=KneekuraDebugDecisionHooks.originalActivityRequirement(brain,Activity.REST,"IF_POSSIBLE",()->{KneekuraDebugDecisionHooks.originalActivityRequirementContains(brain,(Map<?,?>)read(brain,Brain.class,"activityRequirements"),Activity.REST,Activity.REST);return KneekuraDebugDecisionHooks.originalActivityRequirementCheck(brain,module,status,Activity.REST);});KneekuraDebugDecisionHooks.originalActivityUpdate(brain,100,100);return result[0];}
        var m=KneekuraDebugDecisionHooks.class.getDeclaredMethod("originalBrainStartCall",Brain.class,BehaviorControl.class,ServerLevel.class,LivingEntity.class,long.class,BooleanSupplier.class);m.setAccessible(true);return (Boolean)call(m,null,brain,behavior,null,owner,100L,(BooleanSupplier)()->KneekuraDebugDecisionHooks.originalBrainStartCondition(behavior,"HAS_REQUIRED_MEMORIES",null,owner,()->KneekuraDebugDecisionHooks.originalBrainMemoryCheck(behavior,brain,module,status,owner)));
    }
    private static int emitted;private static void emit(List<JsonObject> rows){for(var row:received(rows)){System.out.println("BRAIN_MEMORY_SOURCE_INTEROP:"+new com.google.gson.Gson().toJson(row));emitted++;}}
    private static void compiledHandlers()throws Exception {
        String args="Lnet/minecraft/world/entity/ai/memory/MemoryModuleType;Lnet/minecraft/world/entity/ai/memory/MemoryStatus;",source="checkMemory("+args+")Z";
        var specs=Map.of("kneekura$memorySourceGet",new String[]{"(Ljava/util/Map;Ljava/lang/Object;"+args+")Ljava/lang/Object;","Ljava/util/Map;get(Ljava/lang/Object;)Ljava/lang/Object;","originalMemorySourceGet"},
            "kneekura$memorySourcePresent",new String[]{"(Ljava/util/Optional;"+args+")Z","Ljava/util/Optional;isPresent()Z","originalMemorySourcePresence"},
            "kneekura$memorySourceAbsent",new String[]{"(Ljava/util/Optional;"+args+")Z","Ljava/util/Optional;isPresent()Z","originalMemorySourcePresence"},
            "kneekura$memorySourceReturn",new String[]{"("+args+"Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V",null,"memorySourceBaseReturn"});
        var found=new HashSet<String>();
        try(var bytes=KneekuraDebugBrainMemorySourceSelfTest.class.getResourceAsStream("decisionmixin/KneekuraDebugBrainDecisionMixin.class")){new ClassReader(bytes).accept(new ClassVisitor(Opcodes.ASM9){@Override public MethodVisitor visitMethod(int a,String n,String d,String sig,String[] ex){var spec=specs.get(n);if(spec==null)return null;found.add(n);require(d.equals(spec[0]),"exact appended source method arguments "+n);int[] counts=new int[5];boolean returned=n.equals("kneekura$memorySourceReturn");return new MethodVisitor(Opcodes.ASM9){
            private AnnotationVisitor annotation(){return new AnnotationVisitor(Opcodes.ASM9){@Override public void visit(String key,Object v){if(key.equals("require")){require(v.equals(returned?2:1),"mandatory original source sites");counts[1]++;}if(key.equals("target")){require(v.equals(spec[1]),"exact source call target");counts[2]++;}if(key.equals("ordinal")){require(v.equals(n.endsWith("Present")?0:1),"two distinct original presence sites");counts[3]++;}if(key.equals("value")&&returned){require(v.equals("RETURN"),"normal base return injection");counts[2]++;}}
                @Override public AnnotationVisitor visitArray(String key){if(key.equals("method"))return new AnnotationVisitor(Opcodes.ASM9){@Override public void visit(String ignored,Object v){require(v.equals(source),"exact base method selector");counts[0]++;}};return annotation();}
                @Override public AnnotationVisitor visitAnnotation(String key,String desc){return annotation();}};}
            @Override public AnnotationVisitor visitAnnotation(String d,boolean visible){return d.equals("Lorg/spongepowered/asm/mixin/injection/"+(returned?"Inject":"Redirect")+";")?annotation():null;}
            @Override public void visitMethodInsn(int op,String owner,String name,String desc,boolean itf){if(owner.endsWith("/KneekuraDebugDecisionHooks")){require(op==Opcodes.INVOKESTATIC&&name.equals(spec[2]),"single production source handler delegate");counts[4]++;}}
            @Override public void visitEnd(){require(counts[0]==1&&counts[1]==1&&counts[2]==1&&counts[4]==1&&counts[3]==(n.endsWith("Present")||n.endsWith("Absent")?1:0),"exact mandatory source annotation/delegate "+n);}
        };}},0);}require(found.equals(specs.keySet()),"three mandatory source Redirects and both base return sites");
        int[] gets={0},presence={0};try(var bytes=KneekuraDebugDecisionHooks.class.getResourceAsStream("KneekuraDebugDecisionHooks.class")){new ClassReader(bytes).accept(new ClassVisitor(Opcodes.ASM9){@Override public MethodVisitor visitMethod(int a,String n,String d,String sig,String[] ex){if(!Set.of("originalMemorySourceGet","originalMemorySourcePresence").contains(n))return null;return new MethodVisitor(Opcodes.ASM9){@Override public void visitMethodInsn(int op,String owner,String name,String desc,boolean itf){if(owner.equals("java/util/Map")){require(op==Opcodes.INVOKEINTERFACE&&name.equals("get"),"only original map delegate");gets[0]++;}if(owner.equals("java/util/Optional")){require(op==Opcodes.INVOKEVIRTUAL&&name.equals("isPresent"),"only original presence delegate, no value replay");presence[0]++;}}};}},0);}require(gets[0]==2&&presence[0]==2,"OFF and observed paths each delegate original exactly once");
    }
    public static void main(String[] args)throws Exception {
        net.minecraft.SharedConstants.tryDetectVersion();net.minecraft.server.Bootstrap.bootStrap();var uf=sun.misc.Unsafe.class.getDeclaredField("theUnsafe");uf.setAccessible(true);var unsafe=(sun.misc.Unsafe)uf.get(null);var owner=(Subject)unsafe.allocateInstance(Subject.class);var nav=(Navigation)unsafe.allocateInstance(Navigation.class);field(nav,PathNavigation.class,"mob",owner);field(owner,Mob.class,"navigation",nav);var brain=new ProbeBrain();field(owner,LivingEntity.class,"brain",brain);field(brain,Brain.class,"activityRequirements",Map.of(Activity.REST,Set.of()));var behavior=new MoveToTargetSink();fixture();var slots=new Slots();field(brain,Brain.class,"memories",slots);
        var context=new AtomicReference<>(new KneekuraDebugDecisionBurstBudget.Context("session","run","snapshot",1,0,7,"11111111-2222-3333-4444-555555555555","minecraft:overworld"));var time=new AtomicLong(100);var rows=new ArrayList<JsonObject>();
        for(int mode=0;mode<9;mode++){slots.clear();MemoryStatus status=mode<1?MemoryStatus.VALUE_PRESENT:mode<3?MemoryStatus.REGISTERED:mode<7?(mode<5?MemoryStatus.VALUE_PRESENT:MemoryStatus.VALUE_ABSENT):null;if(mode>0)slots.put(MemoryModuleType.PATH,mode%2==0?Optional.of(new Object()):Optional.empty());brain.baseline=true;slots.gets=brain.calls=0;boolean expected=brain.checkMemory(MemoryModuleType.PATH,status);require(slots.gets==1&&brain.calls==1,"baseline virtual/get once");brain.baseline=false;slots.gets=brain.calls=0;rows.clear();install(owner,Set.of("brain_navigation"),256,524288,context,time,rows);require(observed(false,brain,behavior,owner,MemoryModuleType.PATH,status)==expected&&slots.gets==1&&brain.calls==1,"genuine original branch/result/count unchanged");var facts=received(rows);require(facts.size()==1,"one normal base memory source receipt");var data=facts.get(0).getAsJsonObject("data");require(data.get("baseResult").getAsBoolean()==expected&&data.get("result").getAsBoolean()==expected,"base and virtual returns independently observed");require(data.get("slotStatus").getAsString().equals(mode==0?"NULL":"NON_NULL"),"actual get null/non-null only");require(data.get("presenceStatus").getAsString().equals(mode>=3&&mode<7?"NORMAL_RETURN":"NOT_CALLED"),"actual short-circuit presence call");if(mode>=3&&mode<7)require(data.get("presenceResult").getAsBoolean()==(mode%2==0),"original presence true/false preserved");emit(rows);}
        slots.clear();slots.put(MemoryModuleType.PATH,Optional.empty());brain.invert=true;rows.clear();install(owner,Set.of("brain_navigation"),256,524288,context,time,rows);require(observed(false,brain,behavior,owner,MemoryModuleType.PATH,MemoryStatus.VALUE_PRESENT),"override may invert base result");require(!received(rows).get(0).getAsJsonObject("data").get("baseResult").getAsBoolean()&&received(rows).get(0).getAsJsonObject("data").get("result").getAsBoolean(),"never reconstruct virtual result");emit(rows);brain.invert=false;
        rows.clear();install(owner,Set.of("brain_activity"),256,524288,context,time,rows);require(observed(true,brain,behavior,owner,MemoryModuleType.PATH,MemoryStatus.REGISTERED),"Activity direct source");require(received(rows).size()==1&&received(rows).get(0).getAsJsonObject("data").get("requirementInvocationId").getAsString().equals("activity-requirement:7:1"),"direct Activity requirement ID");emit(rows);
        for(int mode=0;mode<2;mode++){brain.forced=mode==0?true:null;brain.repeated=mode==1;rows.clear();install(owner,Set.of("brain_navigation"),256,524288,context,time,rows);observed(false,brain,behavior,owner,MemoryModuleType.PATH,MemoryStatus.REGISTERED);require(received(rows).isEmpty(),"override without base/repeated base cannot invent single source traversal");}brain.repeated=false;brain.forced=null;
        RuntimeException sentinel=new IllegalStateException("ORIGINAL_GET_FAILURE");slots.failure=sentinel;rows.clear();install(owner,Set.of("brain_navigation"),256,524288,context,time,rows);try{observed(false,brain,behavior,owner,MemoryModuleType.PATH,MemoryStatus.REGISTERED);throw new AssertionError("expected original get exception");}catch(RuntimeException actual){require(actual==sentinel,"original exception same identity");}require(received(rows).isEmpty(),"no normal receipt after original exception");slots.failure=null;
        slots.put(MemoryModuleType.PATH,"BAD_CAST");try{observed(false,brain,behavior,owner,MemoryModuleType.PATH,MemoryStatus.REGISTERED);throw new AssertionError("expected original cast exception");}catch(ClassCastException expected){}require(received(rows).isEmpty(),"original checkcast remains");slots.put(MemoryModuleType.PATH,Optional.empty());for(int mode=0;mode<2;mode++){MemoryModuleType<?> unknown=mode==0?new MemoryModuleType<Object>(Optional.empty()):null;slots.put(unknown,Optional.empty());rows.clear();install(owner,Set.of("brain_navigation"),256,524288,context,time,rows);require(observed(false,brain,behavior,owner,unknown,MemoryStatus.REGISTERED),"unknown/null module original get unchanged");require(received(rows).get(0).getAsJsonObject("data").get("memoryModuleStatus").getAsString().equals("NOT_EXPOSED"),"no registry label replay");emit(rows);}
        rows.clear();var capped=install(owner,Set.of("brain_navigation"),256,524288,context,time,rows);field(capped,KneekuraDebugDecisionHooks.Session.class,"nextMemorySource",255);require(observed(false,brain,behavior,owner,MemoryModuleType.PATH,MemoryStatus.REGISTERED),"final source ID normal call");require(received(rows).get(0).getAsJsonObject("data").get("memorySourceInvocationId").getAsString().equals("memory-source:7:256"),"bounded source ID256");emit(rows);rows.clear();require(observed(false,brain,behavior,owner,MemoryModuleType.PATH,MemoryStatus.REGISTERED)&&received(rows).isEmpty(),"source ID257 suppressed without skipping original call");
        rows.clear();capped=install(owner,Set.of("brain_navigation"),256,524288,context,time,rows);var token=KneekuraDebugDecisionHooks.Session.class.getDeclaredMethod("token",Object.class);token.setAccessible(true);for(int i=0;i<128;i++)call(token,capped,new Object());require(observed(false,brain,behavior,owner,MemoryModuleType.PATH,MemoryStatus.REGISTERED),"component exhaustion normal call");require(received(rows).get(0).getAsJsonObject("data").get("instanceIdentityStatus").getAsString().equals("NOT_EXPOSED"),"unknown raw component at128 cap");emit(rows);
        rows.clear();install(owner,Set.of("brain_navigation"),256,524288,context,time,rows);brain.during=()->{brain.during=null;try{observed(false,brain,behavior,owner,MemoryModuleType.PATH,MemoryStatus.REGISTERED);}catch(Exception e){throw new AssertionError(e);}};require(observed(false,brain,behavior,owner,MemoryModuleType.PATH,MemoryStatus.REGISTERED),"nested normal call");require(received(rows).size()==2&&received(rows).get(0).getAsJsonObject("data").get("memorySourceInvocationId").getAsString().endsWith(":2")&&received(rows).get(1).getAsJsonObject("data").get("memorySourceInvocationId").getAsString().endsWith(":1"),"nested source IDs keep direct parents");emit(rows);
        rows.clear();install(owner,Set.of("brain_activity"),256,524288,context,time,rows);field(owner,Mob.class,"navigation",null);require(observed(true,brain,behavior,owner,MemoryModuleType.PATH,MemoryStatus.REGISTERED)&&received(rows).size()==1,"Activity source has no additional Nav gate");emit(rows);field(owner,Mob.class,"navigation",nav);
        for(String fence:List.of("OFF","CHANNEL","TIME","BRAIN","MAP","NAV_OWNER","CLEAR","REARM","DEPTH")){rows.clear();time.set(100);field(owner,LivingEntity.class,"brain",brain);field(brain,Brain.class,"memories",slots);field(nav,PathNavigation.class,"mob",owner);var session=install(owner,Set.of(fence.equals("CHANNEL")?"brain":"brain_navigation"),256,524288,context,time,rows);if(fence.equals("OFF"))KneekuraDebugDecisionHooks.clear("OFF");if(fence.equals("DEPTH"))field(session,KneekuraDebugDecisionHooks.Session.class,"memorySourceDepth",8);brain.during=()->{brain.during=null;switch(fence){case "TIME"->time.set(201);case "BRAIN"->field(owner,LivingEntity.class,"brain",new ProbeBrain());case "NAV_OWNER"->field(nav,PathNavigation.class,"mob",null);case "CLEAR"->KneekuraDebugDecisionHooks.clear("CLEAR");case "REARM"->{try{install(owner,Set.of("brain_navigation"),256,524288,context,time,new ArrayList<>());}catch(Exception e){throw new AssertionError(e);}}default->{}}};if(fence.equals("MAP"))slots.during=()->{slots.during=null;field(brain,Brain.class,"memories",new Slots());};observed(false,brain,behavior,owner,MemoryModuleType.PATH,MemoryStatus.REGISTERED);require(received(rows).isEmpty(),"new source fence "+fence);require(read(session,KneekuraDebugDecisionHooks.Session.class,"memorySourceFrame")==null,"source frame finally cleaned "+fence);}
        time.set(100);field(owner,LivingEntity.class,"brain",brain);field(brain,Brain.class,"memories",slots);field(nav,PathNavigation.class,"mob",owner);brain.during=null;slots.during=null;
        rows.clear();install(owner,Set.of("brain_navigation"),256,524288,context,time,rows);slots.during=()->{slots.during=null;sourceGet(slots,MemoryModuleType.PATH,brain,MemoryModuleType.PATH,MemoryStatus.REGISTERED);sourceReturn(true,brain,MemoryModuleType.PATH,MemoryStatus.REGISTERED);};require(observed(false,brain,behavior,owner,MemoryModuleType.PATH,MemoryStatus.REGISTERED)&&received(rows).size()==1,"arbitrary callbacks inside original map delegate suppressed");
        for(int mode=0;mode<2;mode++){rows.clear();install(owner,Set.of("brain_navigation"),mode==0?1:256,mode==0?524288:1,context,time,rows);require(observed(false,brain,behavior,owner,MemoryModuleType.PATH,MemoryStatus.REGISTERED),"finite budgets preserve original normal call");require(mode==0?rows.size()==1&&received(rows).size()==1:rows.isEmpty(),"event1/byte1 finite capture");}
        for(int mode=0;mode<8;mode++){rows.clear();var old=context.get();install(owner,Set.of("brain_navigation"),256,524288,context,time,rows);int changed=mode;brain.during=()->{brain.during=null;context.set(new KneekuraDebugDecisionBurstBudget.Context(changed==0?"other":old.sessionId(),changed==1?"other":old.runId(),changed==2?"other":old.snapshotId(),changed==3?2:old.processEpoch(),changed==4?1:old.arenaEpoch(),changed==5?8:old.selectionRevision(),changed==6?"other":old.subjectUuid(),changed==7?"other":old.dimension()));};require(observed(false,brain,behavior,owner,MemoryModuleType.PATH,MemoryStatus.REGISTERED)&&received(rows).isEmpty(),"all exact context fields fence source "+mode);context.set(old);}
        rows.clear();var session=install(owner,Set.of("brain_navigation"),256,524288,context,time,rows);var failure=new AtomicReference<Throwable>();var thread=new Thread(()->{try{require(observed(false,brain,behavior,owner,MemoryModuleType.PATH,MemoryStatus.REGISTERED),"wrong thread original result");}catch(Throwable e){failure.set(e);}});thread.start();thread.join();require(failure.get()==null&&received(rows).isEmpty(),"wrong thread cannot observe source");
        rows.clear();install(owner,Set.of("brain_navigation"),256,524288,context,time,rows);brain.during=()->{brain.during=null;sourceGet(slots,MemoryModuleType.PATH,brain,MemoryModuleType.WALK_TARGET,MemoryStatus.REGISTERED);};require(observed(false,brain,behavior,owner,MemoryModuleType.PATH,MemoryStatus.REGISTERED)&&received(rows).isEmpty(),"mixed original argument invalidates source, preserves original virtual result");
        rows.clear();session=install(owner,Set.of("brain_navigation"),256,524288,context,time,rows);brain.during=()->{brain.during=null;sourcePresence(null,brain,MemoryModuleType.PATH,MemoryStatus.REGISTERED,"VALUE_PRESENT");};try{observed(false,brain,behavior,owner,MemoryModuleType.PATH,MemoryStatus.REGISTERED);throw new AssertionError("expected original null presence exception");}catch(NullPointerException expected){}require(received(rows).isEmpty()&&read(session,KneekuraDebugDecisionHooks.Session.class,"memorySourceFrame")==null,"null original delegate throws and finally cleans source");
        rows.clear();var snapshot=new KneekuraDebugDecisionSnapshot();snapshot.reset(7);int[] writes={0};session=new KneekuraDebugDecisionHooks.Session(owner,null,null,snapshot,new KneekuraDebugDecisionBurstBudget(context.get(),100,100,256,524288),8,Set.of("brain_navigation"),context::get,time::get,(method,row)->{writes[0]++;throw new java.io.IOException("WRITER_FAILURE");});KneekuraDebugDecisionHooks.install(session);require(observed(false,brain,behavior,owner,MemoryModuleType.PATH,MemoryStatus.REGISTERED)&&writes[0]==1&&read(session,KneekuraDebugDecisionHooks.Session.class,"memorySourceFrame")==null,"writer failure leaves original return and cleans source");
        rows.clear();install(owner,Set.of("brain_navigation"),256,524288,context,time,rows);var startCall=KneekuraDebugDecisionHooks.class.getDeclaredMethod("originalBrainStartCall",Brain.class,BehaviorControl.class,ServerLevel.class,LivingEntity.class,long.class,BooleanSupplier.class);startCall.setAccessible(true);slots.gets=brain.calls=0;require((Boolean)call(startCall,null,brain,behavior,null,owner,100L,(BooleanSupplier)()->KneekuraDebugDecisionHooks.originalBrainStartCondition(behavior,"HAS_REQUIRED_MEMORIES",null,owner,()->{for(int i=0;i<9;i++)if(!KneekuraDebugDecisionHooks.originalBrainMemoryCheck(behavior,brain,MemoryModuleType.PATH,MemoryStatus.REGISTERED,owner))return false;return true;})),"nine original checks continue");require(slots.gets==9&&brain.calls==9&&received(rows).size()==8,"finite eight child source packets do not skip ninth original check");for(int i=0;i<8;i++)require(received(rows).get(i).getAsJsonObject("data").get("checkIndex").getAsInt()==i+1,"source prefix index not compressed");var parent=rows.stream().filter(x->x.get("kind").getAsString().equals("BRAIN_PATH_MEMORY_REQUIREMENT_RETURN")).findFirst().orElseThrow().getAsJsonObject("data");require(parent.getAsJsonArray("checks").size()==8&&parent.get("checksTruncated").getAsBoolean(),"old requirement prefix/tail payload unchanged");emit(rows);
        compiledHandlers();KneekuraDebugDecisionHooks.clear("SELFTEST_DONE");System.out.println("Original Brain base memory source self-test passed; Gson cases="+emitted);
    }
}
