package com.github.tartaricacid.touhoulittlemaid.sim.debug;
import com.google.gson.*;
import java.nio.file.*;
import java.util.*;
import java.io.IOException;
public final class KneekuraDebugOwnerInputsSelfTest {
 static int checks;
 interface Op{void run()throws Exception;}
 static void reject(Op r,String label)throws Exception{try{r.run();throw new AssertionError(label);}catch(IOException|IllegalArgumentException expected){checks++;}}
 static String write(Path root,String path,JsonElement value)throws Exception{Path f=root.resolve(path);Files.createDirectories(f.getParent());String b=value.toString();Files.writeString(f,b);return KneekuraDebugActionJournal.sha256(b);}
 static JsonArray vector(int...n){JsonArray a=new JsonArray();for(int i:n)a.add(i);return a;}
 record Fixture(Path root,KneekuraDebugEnv.Config config,JsonObject envelope,JsonObject snapshot){}
 static Fixture fixture()throws Exception{
  Path r=Files.createTempDirectory("owner-inputs").toRealPath();Files.createDirectories(r.resolve("control/owner-materials"));
  byte[] build="build".getBytes(),config="config".getBytes(),resource="resource".getBytes();Files.write(r.resolve("control/owner-materials/build.jar"),build);Files.write(r.resolve("control/owner-materials/config.bin"),config);Files.write(r.resolve("control/owner-materials/resources.bin"),resource);
  JsonObject target=new JsonObject();target.addProperty("build_artifact_hash",KneekuraDebugOwnerFiles.sha256(build));target.addProperty("config_hash",KneekuraDebugOwnerFiles.sha256(config));target.addProperty("resource_hash",KneekuraDebugOwnerFiles.sha256(resource));for(String k:List.of("profile_id","index_snapshot_id","dirty_hash"))target.addProperty(k,"a".repeat(64));target.addProperty("source_revision","a".repeat(40));
  JsonObject request=new JsonObject();request.addProperty("schema_version",1);request.addProperty("experiment_id","experiment");request.addProperty("generation",1);request.add("target",target);JsonObject arena=new JsonObject();arena.addProperty("arena_id","arena");arena.addProperty("preset","normal");arena.addProperty("baseline_hash","b".repeat(64));JsonObject bounds=new JsonObject();bounds.add("min",vector(0,64,0));bounds.add("max",vector(4,68,4));arena.add("bounds",bounds);request.add("arena",arena);
  JsonObject subject=new JsonObject();subject.addProperty("subject_id","subject");subject.addProperty("uuid","00000000-0000-0000-0000-000000000001");subject.addProperty("entity_type","minecraft:armor_stand");JsonArray subjects=new JsonArray();subjects.add(subject);request.add("subjects",subjects);request.add("initial_state",new JsonArray());JsonArray actions=new JsonArray();JsonObject action=new JsonObject();action.addProperty("action_id","wait");action.addProperty("operation","wait_ticks");action.addProperty("ticks",1);actions.add(action);request.add("actions",actions);request.add("observation_scopes",new JsonArray());JsonObject rig=new JsonObject();rig.addProperty("mode","none");request.add("visual_rig",rig);request.add("assertions",new JsonArray());JsonObject budgets=new JsonObject();budgets.addProperty("time_budget_ms",1000);budgets.addProperty("max_actions",1);budgets.addProperty("max_captures",0);request.add("budgets",budgets);
  String req=write(r,"control/owner-experiment-request.json",request);
  JsonObject grant=new JsonObject();grant.addProperty("schemaVersion",1);for(String k:List.of("grantId","debugSessionId","runId","runSnapshotId","experimentId","arenaId","leaseId"))grant.addProperty(k,switch(k){case"experimentId"->"experiment";case"arenaId"->"arena";case"debugSessionId"->"session";case"runId"->"run";case"runSnapshotId"->"snapshot";default->k;});grant.addProperty("processEpoch",1);grant.addProperty("handshakeNonce","nonce-0000000000000001");grant.addProperty("requestHash",req);grant.addProperty("generation",1);grant.addProperty("arenaEpoch",0);grant.addProperty("expectedArenaRevision",0);grant.addProperty("baselineHash","b".repeat(64));grant.addProperty("dimensionId","minecraft:overworld");grant.addProperty("disposableWorldName","KNEEKURA_DEBUG_WORLD");grant.add("bounds",bounds);JsonArray camel=new JsonArray();JsonObject cs=new JsonObject();cs.addProperty("subjectId","subject");cs.addProperty("uuid",subject.get("uuid").getAsString());cs.addProperty("entityType","minecraft:armor_stand");camel.add(cs);grant.add("subjects",camel);grant.addProperty("timeBudgetMs",1000);grant.addProperty("maxActions",1);grant.addProperty("maxCaptures",0);JsonArray allowed=new JsonArray();allowed.add("wait_ticks");grant.add("allowedActions",allowed);
  JsonObject descriptor=new JsonObject();descriptor.addProperty("schemaVersion",1);descriptor.addProperty("linkageMode","OBSERVED_CLASS_RESOURCE_AND_CONTAINER_LINKAGE");descriptor.addProperty("targetModId","touhou_little_maid");descriptor.addProperty("buildArtifactHash",target.get("build_artifact_hash").getAsString());descriptor.addProperty("configArtifactHash",target.get("config_hash").getAsString());descriptor.addProperty("resourceArtifactHash",target.get("resource_hash").getAsString());JsonArray members=new JsonArray();JsonObject member=new JsonObject();member.addProperty("className",KneekuraDebugOwnerInputsSelfTest.class.getName());member.addProperty("sha256","a".repeat(64));members.add(member);descriptor.add("classResources",members);
  JsonObject world=new JsonObject();world.addProperty("schemaVersion",1);world.addProperty("registrationId","registered-world");world.addProperty("canonicalWorldRoot",r.toString());world.addProperty("worldName","KNEEKURA_DEBUG_WORLD");world.addProperty("dimensionId","minecraft:overworld");JsonArray permissions=new JsonArray();permissions.add("BOUNDED_DIAGNOSTIC_CONTROL");world.add("permissions",permissions);
  JsonObject envelope=new JsonObject();envelope.addProperty("schemaVersion",1);for(String k:List.of("debugSessionId","runId","runSnapshotId","processEpoch","handshakeNonce"))envelope.add(k,grant.get(k));envelope.addProperty("requestHash",req);envelope.addProperty("grantHash",write(r,"control/owner-grant.json",grant));envelope.addProperty("materialDescriptorHash",write(r,"control/owner-material-descriptor.json",descriptor));envelope.addProperty("worldRegistrationHash",write(r,"control/owner-world-registration.json",world));envelope.addProperty("controlMode","BOUNDED_DIAGNOSTIC_CONTROL");String eh=write(r,"control/owner-envelope.json",envelope);
  JsonObject snapshot=new JsonObject();snapshot.addProperty("schemaVersion",1);snapshot.addProperty("snapshotId","snapshot");snapshot.addProperty("debugSessionId","session");snapshot.addProperty("runId","run");snapshot.addProperty("processEpoch",1);snapshot.addProperty("worldName","KNEEKURA_DEBUG_WORLD");JsonObject runtime=new JsonObject();runtime.addProperty("pid",ProcessHandle.current().pid());JsonObject attestation=new JsonObject();attestation.addProperty("topology","INTEGRATED_SERVER");runtime.add("attestation",attestation);snapshot.add("runtime",runtime);JsonObject tech=new JsonObject();tech.addProperty("request_hash",req);tech.addProperty("experiment_id","experiment");tech.addProperty("generation",1);tech.addProperty("arena_id","arena");tech.addProperty("arena_baseline_hash","b".repeat(64));tech.add("target",target);snapshot.add("techHub",tech);JsonObject bridge=new JsonObject(),intent=new JsonObject();intent.addProperty("envelopeHash",eh);intent.addProperty("scope","BOUNDED_DIAGNOSTIC_CONTROL");intent.addProperty("fullTargetAttestation","NOT_ESTABLISHED");bridge.add("ownerControlIntent",intent);snapshot.add("bridge",bridge);String canonical=KneekuraDebugActionJournal.canonical(snapshot);Files.writeString(r.resolve("run-snapshot.canonical.json"),canonical);snapshot.addProperty("snapshotHash","sha256:"+KneekuraDebugActionJournal.sha256(canonical));write(r,"run-snapshot.json",snapshot);
  var cfg=KneekuraDebugEnv.fromEnvironment(KneekuraDebugOwnerEnvSelfTest.env(r));cfg=new KneekuraDebugEnv.Config(cfg.enabled(),cfg.debugSessionId(),cfg.runId(),cfg.processEpoch(),cfg.runSnapshotId(),cfg.handshakeNonce(),cfg.readyFile(),cfg.runDir(),cfg.runtimeRoot(),cfg.evidenceRawDir(),cfg.targetFile(),cfg.shutdownRequestFile(),cfg.shutdownAckFile(),cfg.worldName(),new KneekuraDebugEnv.OwnerSetup(r.resolve("control/owner-envelope.json"),eh));return new Fixture(r,cfg,envelope,snapshot);
 }
 public static void main(String[] args)throws Exception{
  Fixture f=fixture();var inputs=KneekuraDebugOwnerInputs.load(f.config());if(!inputs.grant().requestHash().equals(f.envelope().get("requestHash").getAsString()))throw new AssertionError("sealed request");checks++;
  final Fixture canonical=f;Files.writeString(f.root().resolve("run-snapshot.canonical.json"),"{}");reject(()->KneekuraDebugOwnerInputs.load(canonical.config()),"canonical drift");
  f=fixture();final Fixture altered=f;Files.writeString(f.root().resolve("control/owner-grant.json"),"{}");reject(()->KneekuraDebugOwnerInputs.load(altered.config()),"grant drift");
  f=fixture();final Fixture material=f;Files.writeString(f.root().resolve("control/owner-materials/config.bin"),"changed");reject(()->KneekuraDebugOwnerInputs.load(material.config()),"config disk drift");
  f=fixture();final Fixture badSnapshot=f;f.snapshot().addProperty("runId","foreign");write(f.root(),"run-snapshot.json",f.snapshot());reject(()->KneekuraDebugOwnerInputs.load(badSnapshot.config()),"snapshot identity drift");
  System.out.println("owner inputs checks="+checks);
 }
}
