package org.kneekura.techhub.warfarewings.physics;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

import static org.kneekura.techhub.warfarewings.physics.Ia133Microkernel.*;

/**
 * Runs every base Warfare Wings aircraft through identical source-microkernel scenarios.
 *
 * Input is the derived current-ANCHOR CSV generated by extract_anchor_aircraft.py.
 * Output is a feature table, not a real-runtime measurement.
 */
public final class AircraftAtlasMain {
    public static final String SCHEMA = "ww.physics.aircraft-atlas.v2";
    private static final World FLAT = new FlatWorld(0.0);

    private AircraftAtlasMain() {}

    record Entry(String aircraftId, String baseId, String role, String faction, String doctrine,
                 Model model, String evidence) {}

    public record Metrics(
            String aircraftId, String baseId, String role, String faction, String doctrine,
            double predictedTopSpeedBps, int timeTo90SpeedTicks,
            double yawChange20TicksDeg, double pitchChange20TicksDeg,
            double turnExitSpeedRetention,
            int ticksTo90Yaw, double equalAngle90SpeedRetention, double distanceTo90YawBlocks,
            double engineSpeed, double yawSpeed, double pitchSpeed,
            double lift, double glideFactor, double durability, double mass,
            double rawDriftDrag, double runtimeFriction,
            String evidence) {}

    public static void main(String[] args) throws Exception {
        if (args.length != 2) {
            throw new IllegalArgumentException("Usage: AircraftAtlasMain INPUT_ANCHOR_CSV OUTPUT_ATLAS_CSV");
        }
        Path input = Path.of(args[0]);
        Path output = Path.of(args[1]);
        List<Entry> entries = load(input);
        if (entries.size() != 24) throw new IllegalStateException("Expected 24 aircraft, got " + entries.size());

        List<Metrics> metrics = new ArrayList<>(entries.size());
        for (Entry entry : entries) metrics.add(evaluate(entry));

        Files.createDirectories(output.toAbsolutePath().getParent());
        try (BufferedWriter writer = Files.newBufferedWriter(output, StandardCharsets.UTF_8)) {
            writer.write(header());
            writer.newLine();
            for (Metrics row : metrics) {
                writer.write(csv(row));
                writer.newLine();
            }
        }

        Metrics fastest = metrics.stream().max((a,b) -> Double.compare(a.predictedTopSpeedBps(), b.predictedTopSpeedBps())).orElseThrow();
        Metrics yaw = metrics.stream().max((a,b) -> Double.compare(a.yawChange20TicksDeg(), b.yawChange20TicksDeg())).orElseThrow();
        Metrics durable = metrics.stream().max((a,b) -> Double.compare(a.durability(), b.durability())).orElseThrow();
        System.out.printf(Locale.ROOT,
                "AircraftAtlas generated %d rows; fastest=%s %.3f b/s; yaw=%s %.3f deg/20t; durability=%s %.2f%n",
                metrics.size(), fastest.aircraftId(), fastest.predictedTopSpeedBps(),
                yaw.aircraftId(), yaw.yawChange20TicksDeg(),
                durable.aircraftId(), durable.durability());
    }

    static List<Entry> load(Path input) throws IOException {
        try (BufferedReader reader = Files.newBufferedReader(input, StandardCharsets.UTF_8)) {
            String header = reader.readLine();
            if (header == null) throw new IllegalArgumentException("empty aircraft dataset");
            String[] names = header.split(",", -1);
            Map<String,Integer> index = new HashMap<>();
            for (int i=0;i<names.length;i++) index.put(names[i], i);

            List<Entry> out = new ArrayList<>();
            String line;
            while ((line = reader.readLine()) != null) {
                if (line.isBlank()) continue;
                String[] c = line.split(",", -1);
                String id = value(c,index,"aircraft_id");
                Model model = new Model(
                        id, value(c,index,"role"), value(c,index,"doctrine"),
                        number(c,index,"effective_engineSpeed"),
                        number(c,index,"effective_yawSpeed"),
                        number(c,index,"effective_pitchSpeed"),
                        number(c,index,"effective_pushSpeed"),
                        number(c,index,"effective_acceleration"),
                        number(c,index,"effective_durability"),
                        number(c,index,"effective_fuel"),
                        number(c,index,"effective_friction"),
                        number(c,index,"effective_glideFactor"),
                        number(c,index,"effective_lift"),
                        number(c,index,"effective_rollFactor"),
                        number(c,index,"effective_groundPitch"),
                        number(c,index,"effective_stabilizer"),
                        number(c,index,"effective_wind"),
                        number(c,index,"effective_mass"),
                        number(c,index,"effective_groundFriction"),
                        number(c,index,"effective_waterFriction"),
                        number(c,index,"effective_rotationDecay"),
                        number(c,index,"effective_horizontalDecay"),
                        number(c,index,"effective_verticalDecay"),
                        number(c,index,"raw_driftDrag"));
                out.add(new Entry(
                        id,
                        value(c,index,"base_id"),
                        value(c,index,"role"),
                        value(c,index,"faction"),
                        value(c,index,"doctrine"),
                        model,
                        value(c,index,"evidence")));
            }
            long unique = out.stream().map(Entry::aircraftId).distinct().count();
            if (unique != out.size()) throw new IllegalStateException("duplicate aircraft IDs");
            return out;
        }
    }

    static Metrics evaluate(Entry entry) {
        Model model = entry.model();

        State top = initialStraight();
        double[] speedHistory = new double[801];
        speedHistory[0] = top.velocity().length() * TICKS_PER_SECOND;
        for (int i=1;i<=800;i++) {
            top = tick(model, top, Control.neutral(1.0), FLAT);
            speedHistory[i] = top.velocity().length() * TICKS_PER_SECOND;
        }
        double predictedTop = speedHistory[800];
        int time90 = firstAtLeast(speedHistory, predictedTop * 0.90);

        State yawStart = warmStraight(model, 600);
        double yawInitial = yawStart.velocity().length() * TICKS_PER_SECOND;
        State yawEnd = run(yawStart, model, new Control(1,0,0,1), 20);
        double yawExit = yawEnd.velocity().length() * TICKS_PER_SECOND;

        State pitchStart = warmStraight(model, 600);
        State pitchEnd = run(pitchStart, model, new Control(0,0,1,1), 20);

        EqualAngleTurn equalAngle = equalAngle90(model);

        return new Metrics(
                entry.aircraftId(), entry.baseId(), entry.role(), entry.faction(), entry.doctrine(),
                predictedTop, time90,
                Math.abs(yawEnd.yawDeg() - yawStart.yawDeg()),
                Math.abs(pitchEnd.pitchDeg() - pitchStart.pitchDeg()),
                yawExit / yawInitial,
                equalAngle.ticks(), equalAngle.speedRetention(), equalAngle.distanceBlocks(),
                model.engineSpeed(), model.yawSpeed(), model.pitchSpeed(),
                model.lift(), model.glideFactor(), model.durability(), model.mass(),
                model.rawDriftDrag(), model.friction(),
                "SOURCE_MICROKERNEL+" + entry.evidence());
    }

    private record EqualAngleTurn(int ticks, double speedRetention, double distanceBlocks) {}

    private static EqualAngleTurn equalAngle90(Model model) {
        State start = warmStraight(model, 600);
        State current = start;
        double initialSpeed = start.velocity().length() * TICKS_PER_SECOND;
        double distance = 0.0;
        Vec3 previous = start.position();

        for (int ticks = 1; ticks <= 400; ticks++) {
            current = tick(model, current, new Control(1,0,0,1), FLAT);
            Vec3 now = current.position();
            double dx = now.x() - previous.x();
            double dy = now.y() - previous.y();
            double dz = now.z() - previous.z();
            distance += Math.sqrt(dx*dx + dy*dy + dz*dz);
            previous = now;

            if (Math.abs(current.yawDeg() - start.yawDeg()) >= 90.0) {
                double exitSpeed = current.velocity().length() * TICKS_PER_SECOND;
                return new EqualAngleTurn(ticks, exitSpeed / initialSpeed, distance);
            }
        }
        throw new IllegalStateException("Aircraft did not reach 90-degree yaw within 400 ticks: " + model.id());
    }

    private static State initialStraight() {
        return new State(
                0, new Vec3(0,1000,0), new Vec3(0,0,0.70),
                0,0,0, 0,0,0, 0,0,0,
                1,0,1, 0,false,false);
    }

    private static State warmStraight(Model model, int ticks) {
        return run(initialStraight(), model, Control.neutral(1.0), ticks);
    }

    private static State run(State state, Model model, Control control, int ticks) {
        State current = state;
        for (int i=0;i<ticks;i++) current = tick(model, current, control, FLAT);
        return current;
    }

    private static int firstAtLeast(double[] values, double threshold) {
        for (int i=0;i<values.length;i++) if (values[i] >= threshold) return i;
        return -1;
    }

    private static String header() {
        return "schema_version,aircraft_id,base_id,role,faction,doctrine," +
                "source_predicted_top_speed_bps,time_to_90_speed_ticks," +
                "yaw_change_20t_deg,pitch_change_20t_deg,turn_exit_speed_retention," +
                "ticks_to_90_yaw,equal_angle_90_speed_retention,distance_to_90_yaw_blocks," +
                "engine_speed,yaw_speed,pitch_speed,lift,glide_factor,durability,mass," +
                "raw_drift_drag,runtime_friction,evidence";
    }

    private static String csv(Metrics r) {
        return String.join(",",
                SCHEMA, r.aircraftId(), r.baseId(), r.role(), r.faction(), r.doctrine(),
                d(r.predictedTopSpeedBps()), Integer.toString(r.timeTo90SpeedTicks()),
                d(r.yawChange20TicksDeg()), d(r.pitchChange20TicksDeg()), d(r.turnExitSpeedRetention()),
                Integer.toString(r.ticksTo90Yaw()), d(r.equalAngle90SpeedRetention()), d(r.distanceTo90YawBlocks()),
                d(r.engineSpeed()), d(r.yawSpeed()), d(r.pitchSpeed()), d(r.lift()), d(r.glideFactor()),
                d(r.durability()), d(r.mass()), d(r.rawDriftDrag()), d(r.runtimeFriction()), r.evidence());
    }

    private static String d(double value) {
        return String.format(Locale.ROOT, "%.12f", value);
    }

    private static String value(String[] cells, Map<String,Integer> index, String name) {
        Integer i = index.get(name);
        if (i == null || i >= cells.length) throw new IllegalArgumentException("Missing column " + name);
        return cells[i];
    }

    private static double number(String[] cells, Map<String,Integer> index, String name) {
        return Double.parseDouble(value(cells,index,name));
    }
}